import XCTest
@testable import VibeBarCore

final class ClaudeSessionAdapterTests: XCTestCase {
    private var home: URL!
    private let adapter = ClaudeSessionAdapter()
    private let sessionID = "11111111-2222-3333-4444-555555555555"

    override func setUpWithError() throws {
        home = FileManager.default.temporaryDirectory
            .appendingPathComponent("VibeBarClaudeSessionTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: home, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: home)
    }

    // MARK: - Fixtures

    /// `~/.claude/projects/-Users-example-proj/<id>.jsonl`, mirroring the
    /// real encoded-cwd directory layout.
    @discardableResult
    private func writeSession(
        lines: [String],
        root: String = ".claude/projects",
        project: String = "-Users-example-proj",
        fileName: String? = nil
    ) throws -> URL {
        let directory = home
            .appendingPathComponent(root, isDirectory: true)
            .appendingPathComponent(project, isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appendingPathComponent(fileName ?? "\(sessionID).jsonl")
        try (lines.joined(separator: "\n") + "\n").write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private func userLine(_ content: String, isMeta: Bool = false, timestamp: String = "2026-01-01T00:00:01.000Z") -> String {
        """
        {"type":"user","isMeta":\(isMeta),"timestamp":"\(timestamp)","sessionId":"\(sessionID)",\
        "cwd":"/Users/example/proj","message":{"role":"user","content":\(jsonString(content))}}
        """
    }

    private func assistantLine(_ text: String, tool: String? = nil, timestamp: String = "2026-01-01T00:00:02.000Z") -> String {
        var blocks = "{\"type\":\"text\",\"text\":\(jsonString(text))}"
        if let tool {
            blocks += ",{\"type\":\"tool_use\",\"name\":\(jsonString(tool)),\"input\":{}}"
        }
        return """
        {"type":"assistant","timestamp":"\(timestamp)","sessionId":"\(sessionID)",\
        "cwd":"/Users/example/proj","message":{"role":"assistant","content":[\(blocks)]}}
        """
    }

    private func toolResultLine(_ text: String, timestamp: String = "2026-01-01T00:00:03.000Z") -> String {
        """
        {"type":"user","timestamp":"\(timestamp)","sessionId":"\(sessionID)",\
        "cwd":"/Users/example/proj","message":{"role":"user","content":\
        [{"type":"tool_result","tool_use_id":"toolu_1","content":[{"type":"text","text":\(jsonString(text))}]}]}}
        """
    }

    private func customTitleLine(_ title: String) -> String {
        "{\"type\":\"custom-title\",\"customTitle\":\(jsonString(title)),\"sessionId\":\"\(sessionID)\"}"
    }

    private func jsonString(_ value: String) -> String {
        let data = try! JSONSerialization.data(withJSONObject: [value], options: [])
        var text = String(decoding: data, as: UTF8.self)
        text.removeFirst()
        text.removeLast()
        return text
    }

    private var conversationLines: [String] {
        [
            userLine("Caveat: The messages below were generated by the user while running local commands. DO NOT respond to them.", isMeta: true),
            userLine("<command-name>/clear</command-name>\n<command-message>clear</command-message>"),
            userLine("Wire up the session list"),
            assistantLine("On it.", tool: "Read"),
            toolResultLine("file contents"),
            assistantLine("Done.")
        ]
    }

    // MARK: - Metadata

    func testTitlePrefersTheFirstRealUserPromptOverCommandEnvelopes() throws {
        let url = try writeSession(lines: conversationLines)
        let summary = try adapter.extractMetadata(fileURL: url)

        XCTAssertEqual(summary.title, "Wire up the session list")
        XCTAssertEqual(summary.sessionID, sessionID)
        XCTAssertEqual(summary.projectDir, "/Users/example/proj")
        XCTAssertEqual(summary.provider, .claude)
        XCTAssertEqual(summary.id, "claude:\(sessionID):\(url.path)")
        XCTAssertEqual(summary.messageCount, conversationLines.count)
        XCTAssertEqual(summary.createdAt, ISO8601DateFormatter.vibeBarTest.date(from: "2026-01-01T00:00:01.000Z"))
    }

    /// A forked / "continued" session keeps its ancestors' lines — with the
    /// ancestors' `sessionId` — ahead of its own. `claude --resume` takes the
    /// file's UUID, so that is the id the row must carry.
    func testForkedSessionUsesTheFileNameNotTheInheritedSessionIdField() throws {
        let forkID = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
        let url = try writeSession(lines: conversationLines, fileName: "\(forkID).jsonl")
        let summary = try adapter.extractMetadata(fileURL: url)

        XCTAssertEqual(summary.sessionID, forkID)
        XCTAssertNotEqual(summary.sessionID, sessionID)
        XCTAssertEqual(summary.id, "claude:\(forkID):\(url.path)")
    }

    func testPinnedCustomTitleWinsOverTheFirstUserPrompt() throws {
        let url = try writeSession(lines: conversationLines + [customTitleLine("Pinned title")])
        XCTAssertEqual(try adapter.extractMetadata(fileURL: url).title, "Pinned title")
    }

    func testLatestCustomTitleWins() throws {
        let url = try writeSession(lines: conversationLines + [
            customTitleLine("First title"),
            customTitleLine("Second title")
        ])
        XCTAssertEqual(try adapter.extractMetadata(fileURL: url).title, "Second title")
    }

    func testTitleFallsBackToTheProjectFolderName() throws {
        let url = try writeSession(lines: [
            userLine("<command-name>/clear</command-name>"),
            assistantLine("Nothing to do.")
        ])
        XCTAssertEqual(try adapter.extractMetadata(fileURL: url).title, "proj")
    }

    func testSummaryUsesTheLastMessageText() throws {
        let url = try writeSession(lines: conversationLines)
        XCTAssertEqual(try adapter.extractMetadata(fileURL: url).summary, "Done.")
    }

    func testMalformedLinesAreSkippedRatherThanThrown() throws {
        let url = try writeSession(lines: ["{ not json", userLine("Real prompt"), "}{"])
        let summary = try adapter.extractMetadata(fileURL: url)
        XCTAssertEqual(summary.title, "Real prompt")
    }

    func testLargeFileReportsAnUnknownMessageCount() throws {
        let padding = String(repeating: "y", count: 200)
        var lines = [userLine("First prompt")]
        lines += (0..<200).map { assistantLine("chunk \($0) \(padding)") }
        let url = try writeSession(lines: lines)

        let summary = try adapter.extractMetadata(fileURL: url)
        XCTAssertEqual(summary.messageCount, SessionSummary.unknownMessageCount)
        XCTAssertFalse(summary.hasKnownMessageCount)
        XCTAssertEqual(summary.title, "First prompt")
    }

    // MARK: - Discovery

    func testDiscoverySkipsSubagentSidecarFiles() throws {
        let url = try writeSession(lines: conversationLines)
        let sidecar = url.deletingPathExtension().appendingPathComponent("subagents", isDirectory: true)
        try FileManager.default.createDirectory(at: sidecar, withIntermediateDirectories: true)
        try "{}\n".write(to: sidecar.appendingPathComponent("agent-abc123.jsonl"),
                         atomically: true, encoding: .utf8)

        let found = adapter.discoverSessionFiles(homeDirectory: home.path)
        XCTAssertEqual(found.map(SessionTestPaths.canonical), [SessionTestPaths.canonical(url)])
    }

    func testDiscoveryCoversTheAlternateConfigRoot() throws {
        let primary = try writeSession(lines: conversationLines)
        let alternate = try writeSession(
            lines: conversationLines,
            root: ".config/claude/projects",
            fileName: "99999999-2222-3333-4444-555555555555.jsonl"
        )
        let found = Set(adapter.discoverSessionFiles(homeDirectory: home.path).map(SessionTestPaths.canonical))
        XCTAssertEqual(found, [SessionTestPaths.canonical(primary), SessionTestPaths.canonical(alternate)])
        XCTAssertEqual(adapter.roots(homeDirectory: home.path).count, 2)
    }

    func testDiscoveryToleratesMissingDirectories() {
        XCTAssertTrue(adapter.discoverSessionFiles(homeDirectory: home.path).isEmpty)
    }

    // MARK: - Transcript

    func testTranscriptRelabelsToolResultOnlyUserTurns() throws {
        let url = try writeSession(lines: conversationLines)
        let document = try adapter.parseTranscript(fileURL: url, range: nil)

        // Only `isMeta` lines are dropped: a slash command the user
        // typed is still part of the transcript, even though it is not
        // a candidate title.
        XCTAssertEqual(document.messages.map(\.role), [.user, .user, .assistant, .tool, .assistant])
        XCTAssertEqual(document.messages.map(\.text), [
            "<command-name>/clear</command-name>\n<command-message>clear</command-message>",
            "Wire up the session list",
            "On it.\n[Tool: Read]",
            "file contents",
            "Done."
        ])
        XCTAssertEqual(document.totalMessageCount, 5)
        XCTAssertFalse(document.truncated)
        XCTAssertEqual(document.messages.map(\.seq), [0, 1, 2, 3, 4])
    }

    func testTranscriptSkipsMetaLinesAndEmptyMessages() throws {
        let url = try writeSession(lines: [
            userLine("Caveat: meta preamble", isMeta: true),
            userLine(""),
            userLine("Real prompt")
        ])
        let document = try adapter.parseTranscript(fileURL: url, range: nil)
        XCTAssertEqual(document.messages.map(\.text), ["Real prompt"])
    }

    func testTranscriptHonorsARangeOfMessageIndexes() throws {
        let url = try writeSession(lines: conversationLines)
        let document = try adapter.parseTranscript(fileURL: url, range: 2..<4)

        XCTAssertEqual(document.messages.map(\.role), [.assistant, .tool])
        XCTAssertEqual(document.messages.map(\.seq), [2, 3])
        XCTAssertEqual(document.totalMessageCount, 5)
        XCTAssertTrue(document.truncated)
    }

    func testTranscriptClampsAnOutOfBoundsRange() throws {
        let url = try writeSession(lines: conversationLines)
        let document = try adapter.parseTranscript(fileURL: url, range: 2..<99)
        XCTAssertEqual(document.messages.count, 3)
        XCTAssertTrue(document.truncated)
    }

    // MARK: - Deletion plan

    func testDeletionPlanIncludesTheSubagentSidecarDirectory() throws {
        let url = try writeSession(lines: conversationLines)
        let sidecar = url.deletingPathExtension()
        try FileManager.default.createDirectory(at: sidecar, withIntermediateDirectories: true)

        let summary = try adapter.extractMetadata(fileURL: url)
        let plan = try adapter.deletionPlan(for: summary, homeDirectory: home.path)

        XCTAssertEqual(plan.pathsToRemove, [url.path, sidecar.path])
        XCTAssertEqual(plan.validationSourcePath, url.path)
        XCTAssertEqual(plan.expectedSessionID, sessionID)
    }

    func testDeletionPlanIsJustTheFileWhenNoSidecarExists() throws {
        let url = try writeSession(lines: conversationLines)
        let summary = try adapter.extractMetadata(fileURL: url)
        XCTAssertEqual(try adapter.deletionPlan(for: summary, homeDirectory: home.path).pathsToRemove,
                       [url.path])
    }
}

/// Temp directories live under `/var`, a symlink to `/private/var`, and
/// directory enumeration reports the resolved form. Compare canonical
/// paths so fixtures and discovery results line up.
enum SessionTestPaths {
    static func canonical(_ url: URL) -> String {
        url.resolvingSymlinksInPath().standardizedFileURL.path
    }
}

extension ISO8601DateFormatter {
    static let vibeBarTest: ISO8601DateFormatter = {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return formatter
    }()
}
