import XCTest
import SQLite3
@testable import VibeBarCore

final class SessionIndexServiceTests: XCTestCase {
    private var home: URL!
    private var databaseURL: URL!
    private let claudeID = "11111111-2222-3333-4444-555555555555"
    private let codexID = "019c2215-0f3c-7f72-89e3-92598c209589"
    private let geminiHash = "projecthash"

    override func setUpWithError() throws {
        home = FileManager.default.temporaryDirectory
            .appendingPathComponent("VibeBarSessionIndexServiceTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: home, withIntermediateDirectories: true)
        databaseURL = home.appendingPathComponent("session_index.sqlite3")
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: home)
    }

    // MARK: - Fixtures

    private func write(_ contents: String, to relativePath: String) throws -> URL {
        let url = home.appendingPathComponent(relativePath)
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(), withIntermediateDirectories: true
        )
        try contents.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    @discardableResult
    private func writeClaudeSession(prompt: String = "Wire up the session list") throws -> URL {
        let lines = [
            """
            {"type":"user","isMeta":true,"timestamp":"2026-01-01T00:00:00.000Z",\
            "sessionId":"\(claudeID)","cwd":"/Users/example/proj","message":{"role":"user",\
            "content":"Caveat: The messages below were generated by the user while running local commands. DO NOT respond to them."}}
            """,
            """
            {"type":"user","timestamp":"2026-01-01T00:00:01.000Z","sessionId":"\(claudeID)",\
            "cwd":"/Users/example/proj","message":{"role":"user","content":\
            \(JSONFixture.string("<command-name>/clear</command-name>"))}}
            """,
            """
            {"type":"user","timestamp":"2026-01-01T00:00:02.000Z","sessionId":"\(claudeID)",\
            "cwd":"/Users/example/proj","message":{"role":"user","content":\(JSONFixture.string(prompt))}}
            """,
            """
            {"type":"assistant","timestamp":"2026-01-01T00:00:03.000Z","sessionId":"\(claudeID)",\
            "cwd":"/Users/example/proj","message":{"role":"assistant","content":[\
            {"type":"text","text":"On it, indexing 中文内容 as well."},\
            {"type":"tool_use","name":"Read","input":{}}]}}
            """,
            """
            {"type":"user","timestamp":"2026-01-01T00:00:04.000Z","sessionId":"\(claudeID)",\
            "cwd":"/Users/example/proj","message":{"role":"user","content":[\
            {"type":"tool_result","tool_use_id":"toolu_1","content":[\
            {"type":"text","text":"secret tool output that must not be indexed"}]}]}}
            """
        ]
        return try write(
            lines.joined(separator: "\n") + "\n",
            to: ".claude/projects/-Users-example-proj/\(claudeID).jsonl"
        )
    }

    @discardableResult
    private func writeCodexRollout() throws -> URL {
        let ideEnvelope = """
        # Context from my IDE setup:\\nopen file: /Users/example/proj/main.swift\\n\
        ## My request for Codex:\\nRefactor the rollout parser
        """
        let lines = [
            """
            {"type":"session_meta","timestamp":"2026-02-03T13:58:51.000Z","payload":\
            {"id":"\(codexID)","cwd":"/Users/example/other"}}
            """,
            """
            {"type":"response_item","timestamp":"2026-02-03T13:58:52.000Z","payload":\
            {"type":"message","role":"user","content":[{"type":"input_text","text":"\(ideEnvelope)"}]}}
            """,
            """
            {"type":"response_item","timestamp":"2026-02-03T13:58:53.000Z","payload":\
            {"type":"function_call","name":"shell","arguments":"{}"}}
            """,
            """
            {"type":"response_item","timestamp":"2026-02-03T13:58:54.000Z","payload":\
            {"type":"function_call_output","output":"tool output that must not be indexed"}}
            """
        ]
        return try write(
            lines.joined(separator: "\n") + "\n",
            to: ".codex/sessions/2026/02/03/rollout-2026-02-03T13-58-51-\(codexID).jsonl"
        )
    }

    @discardableResult
    private func writeGeminiSession() throws -> URL {
        let json = """
        {"sessionId":"session-gemini-1","startTime":"2026-03-01T10:00:00.000Z",\
        "lastUpdated":"2026-03-01T10:05:00.000Z","messages":[\
        {"type":"user","timestamp":"2026-03-01T10:00:00.000Z","content":"Check the gemini transcript"},\
        {"type":"gemini","timestamp":"2026-03-01T10:00:30.000Z","content":"Checked."}]}
        """
        _ = try write("/Users/example/gemini-proj\n", to: ".gemini/tmp/\(geminiHash)/.project_root")
        return try write(json, to: ".gemini/tmp/\(geminiHash)/chats/session-2026-03-01.json")
    }

    private func makeService(bodyIndexing: Bool = true) throws -> (SessionIndexService, SessionIndexStore) {
        let store = try SessionIndexStore(url: databaseURL)
        let service = SessionIndexService(
            homeDirectory: home.path,
            store: store,
            registry: SessionProviderRegistry.standard(homeDirectory: home.path),
            bodyIndexing: { bodyIndexing }
        )
        return (service, store)
    }

    // MARK: - Refresh

    func testInitialRefreshIndexesEveryProvider() async throws {
        try writeClaudeSession()
        try writeCodexRollout()
        try writeGeminiSession()
        let (service, store) = try makeService()

        await service.refreshIndex()

        let summaries = try await store.allSummaries()
        XCTAssertEqual(Set(summaries.map(\.provider)), [.claude, .codex, .gemini])
        XCTAssertEqual(summaries.count, 3)
        let claude = try XCTUnwrap(summaries.first { $0.provider == .claude })
        XCTAssertEqual(claude.title, "Wire up the session list")
        XCTAssertEqual(claude.projectDir, "/Users/example/proj")
        let gemini = try XCTUnwrap(summaries.first { $0.provider == .gemini })
        XCTAssertEqual(gemini.projectDir, "/Users/example/gemini-proj")
    }

    func testSearchReachesTranscriptBodiesAcrossProviders() async throws {
        try writeClaudeSession()
        try writeGeminiSession()
        let (service, _) = try makeService()
        await service.refreshIndex()

        let claudeHits = try await service.search("indexing 中文")
        XCTAssertEqual(claudeHits.map(\.summary.provider), [.claude])
        XCTAssertEqual(claudeHits.first?.matchedSeq, 2)

        let geminiHits = try await service.search("gemini transcript")
        XCTAssertEqual(geminiHits.map(\.summary.provider), [.gemini])
    }

    func testEnvelopeAndToolTextNeverReachTheIndex() async throws {
        try writeClaudeSession()
        try writeCodexRollout()
        let (service, store) = try makeService()
        await service.refreshIndex()

        for needle in [
            "Caveat: The messages",       // Claude meta preamble
            "command-name",               // slash-command envelope
            "Context from my IDE setup",  // Codex IDE envelope
            "must not be indexed",        // tool output (role .tool)
            "[Tool: Read]"                // rendered tool call inside an assistant turn
        ] {
            // A metadata hit is still possible — the Claude adapter's row
            // `summary` is literally the last transcript line, tool output
            // included — but nothing here may match a message body.
            let hits = try await service.search(needle)
            XCTAssertTrue(
                hits.allSatisfy { $0.matchedSeq == nil },
                "\(needle) should not be in the body index"
            )
        }

        // The user's own sentence from inside the Codex IDE envelope
        // survives; only the editor preamble is stripped.
        let request = try await service.search("Refactor the rollout parser")
        XCTAssertEqual(request.map(\.summary.provider), [.codex])

        // Three excerpts survive across both providers: Claude's slash
        // command is dropped as an envelope, its prompt and its
        // assistant prose are kept, and Codex contributes only the
        // request that followed its IDE preamble.
        let indexed = try await store.messageCount()
        XCTAssertEqual(indexed, 3)
    }

    func testUnchangedFilesAreNotReindexed() async throws {
        let claude = try writeClaudeSession()
        let codex = try writeCodexRollout()
        let (service, store) = try makeService()
        await service.refreshIndex()

        let before = try cursors()
        XCTAssertEqual(before.count, 2)

        // Rewrite only the Claude session, with a new prompt.
        try writeClaudeSession(prompt: "Reworded prompt for the second pass")
        await service.refreshIndex()

        let after = try cursors()
        XCTAssertNotEqual(before[claude.lastPathComponent], after[claude.lastPathComponent])
        XCTAssertEqual(before[codex.lastPathComponent], after[codex.lastPathComponent])

        let reworded = try await service.search("Reworded prompt")
        XCTAssertEqual(reworded.count, 1)
        let stale = try await service.search("Wire up the session list")
        XCTAssertTrue(stale.isEmpty)
        let sessions = try await store.sessionCount()
        XCTAssertEqual(sessions, 2)
    }

    func testDeletedFilesArePrunedOnTheNextRefresh() async throws {
        let claude = try writeClaudeSession()
        try writeGeminiSession()
        let (service, store) = try makeService()
        await service.refreshIndex()
        let before = try await store.sessionCount()
        XCTAssertEqual(before, 2)

        try FileManager.default.removeItem(at: claude)
        await service.refreshIndex()

        let remaining = try await store.allSummaries()
        XCTAssertEqual(remaining.map(\.provider), [.gemini])
        let messages = try await service.search("indexing 中文")
        XCTAssertTrue(messages.isEmpty)
        let remainingCursors = try cursors()
        XCTAssertEqual(remainingCursors.count, 1)
        XCTAssertNil(remainingCursors[claude.lastPathComponent])
    }

    /// Scan cursors keyed by file name. Directory enumeration reports
    /// `/private/var/…` while the fixtures build `/var/…`, so the tests
    /// compare on the file name rather than on a hashed absolute path.
    private func cursors() throws -> [String: Int64] {
        var handle: OpaquePointer?
        guard sqlite3_open_v2(databaseURL.path, &handle, SQLITE_OPEN_READONLY, nil) == SQLITE_OK,
              let handle
        else { throw CocoaError(.fileReadUnknown) }
        defer { sqlite3_close_v2(handle) }
        var statement: OpaquePointer?
        guard sqlite3_prepare_v2(
            handle, "SELECT path, mtime_ns, size FROM session_files", -1, &statement, nil
        ) == SQLITE_OK, let statement else { throw CocoaError(.fileReadUnknown) }
        defer { sqlite3_finalize(statement) }
        var out: [String: Int64] = [:]
        while sqlite3_step(statement) == SQLITE_ROW {
            guard let raw = sqlite3_column_text(statement, 0) else { continue }
            let name = URL(fileURLWithPath: String(cString: raw)).lastPathComponent
            out[name] = sqlite3_column_int64(statement, 1) &+ sqlite3_column_int64(statement, 2)
        }
        return out
    }

    func testBodyIndexingOffIndexesMetadataOnly() async throws {
        try writeClaudeSession()
        let (service, store) = try makeService(bodyIndexing: false)

        await service.refreshIndex()

        let sessions = try await store.sessionCount()
        let messages = try await store.messageCount()
        XCTAssertEqual(sessions, 1)
        XCTAssertEqual(messages, 0)

        let body = try await service.search("indexing 中文")
        XCTAssertTrue(body.isEmpty)
        // The title still comes from the transcript's first real prompt,
        // so metadata search keeps working.
        let metadata = try await service.search("session list")
        XCTAssertEqual(metadata.count, 1)
        XCTAssertNil(metadata.first?.snippet)
    }

    func testTurningBodyIndexingOffDropsPreviouslyIndexedBodies() async throws {
        try writeClaudeSession()
        let store = try SessionIndexStore(url: databaseURL)
        let enabled = SwitchBox(value: true)
        let service = SessionIndexService(
            homeDirectory: home.path,
            store: store,
            registry: SessionProviderRegistry.standard(homeDirectory: home.path),
            bodyIndexing: { enabled.value }
        )

        await service.refreshIndex()
        let indexed = try await store.messageCount()
        XCTAssertGreaterThan(indexed, 0)

        enabled.value = false
        await service.refreshIndex()

        let dropped = try await store.messageCount()
        let sessions = try await store.sessionCount()
        XCTAssertEqual(dropped, 0)
        XCTAssertEqual(sessions, 1)

        // Switching back on has to backfill: the file's fingerprint never
        // moved, so only the mode change can trigger a re-read.
        enabled.value = true
        await service.refreshIndex()

        let backfilled = try await store.messageCount()
        XCTAssertEqual(backfilled, indexed)
        let hits = try await service.search("indexing 中文")
        XCTAssertEqual(hits.count, 1)
    }

    func testProgressCountsEveryDiscoveredFile() async throws {
        try writeClaudeSession()
        try writeCodexRollout()
        try writeGeminiSession()
        let (service, _) = try makeService()

        let recorder = ProgressRecorder()
        await service.refreshIndex { done, total in recorder.record(done, total) }

        XCTAssertEqual(recorder.steps, [(1, 3), (2, 3), (3, 3)].map { Step(done: $0.0, total: $0.1) })
    }

    func testUnreadableFilesAreSkippedWithoutSinkingTheSweep() async throws {
        try writeClaudeSession()
        _ = try write("not json at all\n", to: ".claude/projects/-Users-example-proj/broken.jsonl")
        _ = try write("", to: ".gemini/tmp/\(geminiHash)/chats/session-empty.json")
        let (service, store) = try makeService()

        await service.refreshIndex()

        let summaries = try await store.allSummaries()
        XCTAssertEqual(summaries.map(\.provider), [.claude])
        XCTAssertEqual(summaries.first?.sessionID, claudeID)
    }

    // MARK: - Excerpt policy

    func testExcerptsCapPerMessageAndPerSession() {
        let long = String(repeating: "词", count: 5_000)
        let document = TranscriptDocument(
            messages: (0..<200).map {
                SessionMessage(seq: $0, role: .user, text: long, timestamp: nil)
            },
            totalMessageCount: 200,
            truncated: false
        )

        let excerpts = SessionIndexService.excerpts(from: document, provider: .claude)
        XCTAssertTrue(excerpts.allSatisfy {
            $0.excerpt.count <= SessionIndexService.maxExcerptCharacters + 1
        })
        let bytes = excerpts.reduce(0) { $0 + $1.excerpt.utf8.count }
        XCTAssertLessThanOrEqual(bytes, SessionIndexService.maxSessionExcerptBytes)
        XCTAssertGreaterThan(excerpts.count, 0)
        XCTAssertLessThan(excerpts.count, 200)
    }

    func testExcerptsKeepOnlyUserAndAssistantTurns() {
        let document = TranscriptDocument(
            messages: [
                SessionMessage(seq: 0, role: .system, text: "system preamble", timestamp: nil),
                SessionMessage(seq: 1, role: .user, text: "a real question", timestamp: nil),
                SessionMessage(seq: 2, role: .tool, text: "tool output", timestamp: nil),
                SessionMessage(seq: 3, role: .assistant, text: "a real answer\n[Tool: Read]", timestamp: nil),
                SessionMessage(seq: 4, role: .assistant, text: "[Tool: Bash]", timestamp: nil),
                SessionMessage(seq: 5, role: .other, text: "Turn — model · in 1 · out 2", timestamp: nil)
            ],
            totalMessageCount: 6,
            truncated: false
        )

        let excerpts = SessionIndexService.excerpts(from: document, provider: .claude)
        XCTAssertEqual(excerpts.map(\.seq), [1, 3])
        XCTAssertEqual(excerpts.map(\.excerpt), ["a real question", "a real answer"])
    }
}

/// `(done, total)` pair with equatable semantics for the progress test.
private struct Step: Equatable {
    let done: Int
    let total: Int
}

private final class ProgressRecorder: @unchecked Sendable {
    private let lock = NSLock()
    private var storage: [Step] = []

    var steps: [Step] {
        lock.lock()
        defer { lock.unlock() }
        return storage
    }

    func record(_ done: Int, _ total: Int) {
        lock.lock()
        storage.append(Step(done: done, total: total))
        lock.unlock()
    }
}

private final class SwitchBox: @unchecked Sendable {
    private let lock = NSLock()
    private var storage: Bool

    init(value: Bool) { self.storage = value }

    var value: Bool {
        get {
            lock.lock()
            defer { lock.unlock() }
            return storage
        }
        set {
            lock.lock()
            storage = newValue
            lock.unlock()
        }
    }
}
