// Generated by Scripts/build_localizations.py from Resources/i18n/en.json.
// Do not edit: LocalizationCatalogTests regenerates this file and fails
// on a diff.
//
// This is the *only* way the App target reaches a localized string.
// `L10n.string(_:)` is internal to VibeBarCore on purpose, so a key that
// takes arguments cannot be fetched as a bare format string and filled in
// by hand — the accessor takes named arguments and the generator owns the
// positional order each language happens to need.

import Foundation

extension L10n {
    public enum Common {
        /// `common.date.month.1` — Jan
        public static var dateMonth1: String {
            L10n.string("common.date.month.1")
        }
        /// `common.date.month.10` — Oct
        public static var dateMonth10: String {
            L10n.string("common.date.month.10")
        }
        /// `common.date.month.11` — Nov
        public static var dateMonth11: String {
            L10n.string("common.date.month.11")
        }
        /// `common.date.month.12` — Dec
        public static var dateMonth12: String {
            L10n.string("common.date.month.12")
        }
        /// `common.date.month.2` — Feb
        public static var dateMonth2: String {
            L10n.string("common.date.month.2")
        }
        /// `common.date.month.3` — Mar
        public static var dateMonth3: String {
            L10n.string("common.date.month.3")
        }
        /// `common.date.month.4` — Apr
        public static var dateMonth4: String {
            L10n.string("common.date.month.4")
        }
        /// `common.date.month.5` — May
        public static var dateMonth5: String {
            L10n.string("common.date.month.5")
        }
        /// `common.date.month.6` — Jun
        public static var dateMonth6: String {
            L10n.string("common.date.month.6")
        }
        /// `common.date.month.7` — Jul
        public static var dateMonth7: String {
            L10n.string("common.date.month.7")
        }
        /// `common.date.month.8` — Aug
        public static var dateMonth8: String {
            L10n.string("common.date.month.8")
        }
        /// `common.date.month.9` — Sep
        public static var dateMonth9: String {
            L10n.string("common.date.month.9")
        }
        /// `common.date.monthDayTime` — {month} {day}, {time}
        public static func dateMonthDayTime(month: String, day: Int, time: String) -> String {
            L10n.string("common.date.monthDayTime", month, day, time)
        }
        /// `common.date.monthDayYearTime` — {month} {day}, {year}, {time}
        public static func dateMonthDayYearTime(month: String, day: Int, year: String, time: String) -> String {
            L10n.string("common.date.monthDayYearTime", month, day, year, time)
        }
        /// `common.duration.days` — {days}d
        public static func durationDays(days: Int) -> String {
            L10n.string("common.duration.days", days)
        }
        /// `common.duration.daysHours` — {days}d {hours}h
        public static func durationDaysHours(days: Int, hours: Int) -> String {
            L10n.string("common.duration.daysHours", days, hours)
        }
        /// `common.duration.hours` — {hours}h
        public static func durationHours(hours: Int) -> String {
            L10n.string("common.duration.hours", hours)
        }
        /// `common.duration.hoursMinutes` — {hours}h {minutes}m
        public static func durationHoursMinutes(hours: Int, minutes: Int) -> String {
            L10n.string("common.duration.hoursMinutes", hours, minutes)
        }
        /// `common.duration.lessThanMinute` — <1m
        public static var durationLessThanMinute: String {
            L10n.string("common.duration.lessThanMinute")
        }
        /// `common.duration.minutes` — {minutes}m
        public static func durationMinutes(minutes: Int) -> String {
            L10n.string("common.duration.minutes", minutes)
        }
        /// `common.duration.now` — now
        public static var durationNow: String {
            L10n.string("common.duration.now")
        }
        /// `common.off` — Off
        public static var off: String {
            L10n.string("common.off")
        }
        /// `common.on` — On
        public static var on: String {
            L10n.string("common.on")
        }
        /// `common.openSettings` — Open Settings
        public static var openSettings: String {
            L10n.string("common.openSettings")
        }
        /// `common.percent` — {value}%
        public static func percent(value: Int) -> String {
            L10n.string("common.percent", value)
        }
        /// `common.refresh` — Refresh
        public static var refresh: String {
            L10n.string("common.refresh")
        }
        /// `common.refreshSection` — Refresh this section
        public static var refreshSection: String {
            L10n.string("common.refreshSection")
        }
        /// `common.retry` — Retry
        public static var retry: String {
            L10n.string("common.retry")
        }
        /// `common.updated.daysAgo` — Updated {days, plural, one {1 day} other {# days}} ago
        public static func updatedDaysAgo(days: Int) -> String {
            L10n.string("common.updated.daysAgo", days)
        }
        /// `common.updated.hoursAgo` — Updated {hours, plural, one {1 hour} other {# hours}} ago
        public static func updatedHoursAgo(hours: Int) -> String {
            L10n.string("common.updated.hoursAgo", hours)
        }
        /// `common.updated.justNow` — Updated just now
        public static var updatedJustNow: String {
            L10n.string("common.updated.justNow")
        }
        /// `common.updated.minutesAgo` — Updated {minutes, plural, one {1 minute} other {# minutes}} ago
        public static func updatedMinutesAgo(minutes: Int) -> String {
            L10n.string("common.updated.minutesAgo", minutes)
        }
        /// `common.updated.never` — Never updated
        public static var updatedNever: String {
            L10n.string("common.updated.never")
        }
        /// `common.updated.secondsAgo` — Updated {seconds} seconds ago
        public static func updatedSecondsAgo(seconds: Int) -> String {
            L10n.string("common.updated.secondsAgo", seconds)
        }
    }

    public enum Cost {
        /// `cost.allProviders` — All providers
        public static var allProviders: String {
            L10n.string("cost.allProviders")
        }
        /// `cost.empty.antigravity` — No Antigravity conversation token metadata found yet.
        public static var emptyAntigravity: String {
            L10n.string("cost.empty.antigravity")
        }
        /// `cost.empty.claude` — No Claude CLI sessions found yet.
        public static var emptyClaude: String {
            L10n.string("cost.empty.claude")
        }
        /// `cost.empty.codex` — No Codex CLI sessions found yet.
        public static var emptyCodex: String {
            L10n.string("cost.empty.codex")
        }
        /// `cost.empty.gemini` — No Gemini CLI or chat-history usage found yet.
        public static var emptyGemini: String {
            L10n.string("cost.empty.gemini")
        }
        /// `cost.empty.genericCLI` — No {provider} CLI sessions found yet.
        public static func emptyGenericCLI(provider: String) -> String {
            L10n.string("cost.empty.genericCLI", provider)
        }
        /// `cost.empty.grok` — No Grok session usage found yet.
        public static var emptyGrok: String {
            L10n.string("cost.empty.grok")
        }
        /// `cost.fullCharts` — {title} — Full Charts
        public static func fullCharts(title: String) -> String {
            L10n.string("cost.fullCharts", title)
        }
        /// `cost.gemini.emptyDetail` — Vibe Bar reads live AntiGravity quota from the desktop app when available, then falls back to the installed agy CLI. Cached values are marked stale when neither local source can refresh them.
        public static var geminiEmptyDetail: String {
            L10n.string("cost.gemini.emptyDetail")
        }
        /// `cost.gemini.emptyTitle` — No Gemini or AntiGravity usage found yet.
        public static var geminiEmptyTitle: String {
            L10n.string("cost.gemini.emptyTitle")
        }
        /// `cost.googleAI.empty` — No Gemini Web / AntiGravity usage yet — refresh after signing in to AntiGravity or agy.
        public static var googleAIEmpty: String {
            L10n.string("cost.googleAI.empty")
        }
        /// `cost.googleAI.title` — Google AI Cost
        public static var googleAITitle: String {
            L10n.string("cost.googleAI.title")
        }
        /// `cost.history.allProviders` — All Providers Cost History
        public static var historyAllProviders: String {
            L10n.string("cost.history.allProviders")
        }
        /// `cost.metric.peakDay` — PEAK DAY
        public static var metricPeakDay: String {
            L10n.string("cost.metric.peakDay")
        }
        /// `cost.metric.peakTokenDay` — PEAK TOK DAY
        public static var metricPeakTokenDay: String {
            L10n.string("cost.metric.peakTokenDay")
        }
        /// `cost.metric.sevenDay` — 7-DAY
        public static var metricSevenDay: String {
            L10n.string("cost.metric.sevenDay")
        }
        /// `cost.metric.sevenDayTokens` — 7-DAY TOK
        public static var metricSevenDayTokens: String {
            L10n.string("cost.metric.sevenDayTokens")
        }
        /// `cost.metric.thirtyDay` — 30-DAY
        public static var metricThirtyDay: String {
            L10n.string("cost.metric.thirtyDay")
        }
        /// `cost.metric.thirtyDayTokens` — 30-DAY TOK
        public static var metricThirtyDayTokens: String {
            L10n.string("cost.metric.thirtyDayTokens")
        }
        /// `cost.metric.today` — TODAY
        public static var metricToday: String {
            L10n.string("cost.metric.today")
        }
        /// `cost.metric.todayTokens` — TODAY TOK
        public static var metricTodayTokens: String {
            L10n.string("cost.metric.todayTokens")
        }
        /// `cost.metric.totalCost` — TOTAL COST
        public static var metricTotalCost: String {
            L10n.string("cost.metric.totalCost")
        }
        /// `cost.metric.totalTokens` — TOTAL TOK
        public static var metricTotalTokens: String {
            L10n.string("cost.metric.totalTokens")
        }
        /// `cost.metric.yesterday` — YESTERDAY
        public static var metricYesterday: String {
            L10n.string("cost.metric.yesterday")
        }
        /// `cost.metric.yesterdayTokens` — YESTERDAY TOK
        public static var metricYesterdayTokens: String {
            L10n.string("cost.metric.yesterdayTokens")
        }
        /// `cost.modelRanking.allProvidersAllTime` — All providers · all time
        public static var modelRankingAllProvidersAllTime: String {
            L10n.string("cost.modelRanking.allProvidersAllTime")
        }
        /// `cost.modelRanking.allTime` — All time
        public static var modelRankingAllTime: String {
            L10n.string("cost.modelRanking.allTime")
        }
        /// `cost.modelRanking.rank` — #{rank}
        public static func modelRankingRank(rank: Int) -> String {
            L10n.string("cost.modelRanking.rank", rank)
        }
        /// `cost.modelRanking.title` — Model Ranking
        public static var modelRankingTitle: String {
            L10n.string("cost.modelRanking.title")
        }
        /// `cost.noUsageYet` — No usage yet
        public static var noUsageYet: String {
            L10n.string("cost.noUsageYet")
        }
        /// `cost.notTracked` — Cost history isn't tracked for {provider}.
        public static func notTracked(provider: String) -> String {
            L10n.string("cost.notTracked", provider)
        }
        /// `cost.openFullCharts` — Open full charts
        public static var openFullCharts: String {
            L10n.string("cost.openFullCharts")
        }
        /// `cost.provider.title` — {provider} Cost
        public static func providerTitle(provider: String) -> String {
            L10n.string("cost.provider.title", provider)
        }
        /// `cost.refreshData` — Refresh cost data
        public static var refreshData: String {
            L10n.string("cost.refreshData")
        }
        /// `cost.refreshProvider` — Refresh {provider} cost
        public static func refreshProvider(provider: String) -> String {
            L10n.string("cost.refreshProvider", provider)
        }
        /// `cost.spaceXAI.empty` — No Grok or Cursor usage found yet.
        public static var spaceXAIEmpty: String {
            L10n.string("cost.spaceXAI.empty")
        }
        /// `cost.spaceXAI.title` — SpaceXAI Cost
        public static var spaceXAITitle: String {
            L10n.string("cost.spaceXAI.title")
        }
        /// `cost.timeframe.all` — All
        public static var timeframeAll: String {
            L10n.string("cost.timeframe.all")
        }
        /// `cost.timeframe.month` — 30 days
        public static var timeframeMonth: String {
            L10n.string("cost.timeframe.month")
        }
        /// `cost.timeframe.monthShort` — 30d
        public static var timeframeMonthShort: String {
            L10n.string("cost.timeframe.monthShort")
        }
        /// `cost.timeframe.today` — Today
        public static var timeframeToday: String {
            L10n.string("cost.timeframe.today")
        }
        /// `cost.timeframe.week` — 7 days
        public static var timeframeWeek: String {
            L10n.string("cost.timeframe.week")
        }
        /// `cost.timeframe.weekShort` — 7d
        public static var timeframeWeekShort: String {
            L10n.string("cost.timeframe.weekShort")
        }
        /// `cost.timeframe.yesterday` — Yesterday
        public static var timeframeYesterday: String {
            L10n.string("cost.timeframe.yesterday")
        }
        /// `cost.title` — Cost
        public static var title: String {
            L10n.string("cost.title")
        }
        /// `cost.topModel.share` — {percent}% share
        public static func topModelShare(percent: Int) -> String {
            L10n.string("cost.topModel.share", percent)
        }
        /// `cost.topModel.title` — TOP MODEL
        public static var topModelTitle: String {
            L10n.string("cost.topModel.title")
        }
        /// `cost.topModel.window` — 7D
        public static var topModelWindow: String {
            L10n.string("cost.topModel.window")
        }
    }

    public enum Errors {
        /// `error.credentialRejected` — Credential rejected
        public static var credentialRejected: String {
            L10n.string("error.credentialRejected")
        }
        /// `error.needsLogin` — Needs re-login
        public static var needsLogin: String {
            L10n.string("error.needsLogin")
        }
        /// `error.network` — Network error
        public static var network: String {
            L10n.string("error.network")
        }
        /// `error.networkDetail` — Network error: {reason}
        public static func networkDetail(reason: String) -> String {
            L10n.string("error.networkDetail", reason)
        }
        /// `error.noCredential` — No account found
        public static var noCredential: String {
            L10n.string("error.noCredential")
        }
        /// `error.notImplemented` — Not yet supported
        public static var notImplemented: String {
            L10n.string("error.notImplemented")
        }
        /// `error.parseFailure` — Response format changed
        public static var parseFailure: String {
            L10n.string("error.parseFailure")
        }
        /// `error.rateLimited` — Rate limited, try later
        public static var rateLimited: String {
            L10n.string("error.rateLimited")
        }
        /// `error.unknown` — Error
        public static var unknown: String {
            L10n.string("error.unknown")
        }
        /// `error.unknownDetail` — Error: {reason}
        public static func unknownDetail(reason: String) -> String {
            L10n.string("error.unknownDetail", reason)
        }
    }

    public enum Onboarding {
        /// `onboarding.apiKeys.intro` — These plans are tracked with an API key or a console cookie rather than a CLI login. Tick the ones you have — a ticked provider gets a card on the Misc page — and unfold a row to enter its credential now. Keys and cookies go to your login Keychain.
        public static var apiKeysIntro: String {
            L10n.string("onboarding.apiKeys.intro")
        }
        /// `onboarding.apiKeys.showOnMiscPage` — Show {provider} on the Misc page
        public static func apiKeysShowOnMiscPage(provider: String) -> String {
            L10n.string("onboarding.apiKeys.showOnMiscPage", provider)
        }
        /// `onboarding.back` — Back
        public static var back: String {
            L10n.string("onboarding.back")
        }
        /// `onboarding.continue` — Continue
        public static var `continue`: String {
            L10n.string("onboarding.continue")
        }
        /// `onboarding.cookies.batchScope` — This button covers the four plans above. The console-cookie plans on the next step have their own one-click batch import later, under Settings → Browser Cookies.
        public static var cookiesBatchScope: String {
            L10n.string("onboarding.cookies.batchScope")
        }
        /// `onboarding.cookies.importFromBrowser` — Import from browser
        public static var cookiesImportFromBrowser: String {
            L10n.string("onboarding.cookies.importFromBrowser")
        }
        /// `onboarding.cookies.importGemini` — Import Gemini cookies from browser
        public static var cookiesImportGemini: String {
            L10n.string("onboarding.cookies.importGemini")
        }
        /// `onboarding.cookies.importGrok` — Import Grok cookies from browser
        public static var cookiesImportGrok: String {
            L10n.string("onboarding.cookies.importGrok")
        }
        /// `onboarding.cookies.importing` — Importing…
        public static var cookiesImporting: String {
            L10n.string("onboarding.cookies.importing")
        }
        /// `onboarding.cookies.intro` — Web quotas — the ones the provider shows on its own site — come from the session your browser already has. Vibe Bar reads the cookie stores of the browsers on this Mac (Chrome and other Chromium browsers, Safari, Firefox), keeps only the few cookies each provider needs, and stores them in your login Keychain, never in a plaintext file. macOS may ask once for permission to read a browser's cookie key.
        public static var cookiesIntro: String {
            L10n.string("onboarding.cookies.intro")
        }
        /// `onboarding.cookies.notImported` — Not imported yet
        public static var cookiesNotImported: String {
            L10n.string("onboarding.cookies.notImported")
        }
        /// `onboarding.cookies.openWebViewLogin` — Open WebView login
        public static var cookiesOpenWebViewLogin: String {
            L10n.string("onboarding.cookies.openWebViewLogin")
        }
        /// `onboarding.cookies.saved` — Cookies saved.
        public static var cookiesSaved: String {
            L10n.string("onboarding.cookies.saved")
        }
        /// `onboarding.cookies.signInFirst` — Sign in to chatgpt.com, claude.ai, gemini.google.com or grok.com in your browser first — an import can only find a session that exists. Providers you have not signed in to simply report nothing.
        public static var cookiesSignInFirst: String {
            L10n.string("onboarding.cookies.signInFirst")
        }
        /// `onboarding.done.apiKeyProviders` — API-key providers
        public static var doneApiKeyProviders: String {
            L10n.string("onboarding.done.apiKeyProviders")
        }
        /// `onboarding.done.browserCookies` — Browser cookies
        public static var doneBrowserCookies: String {
            L10n.string("onboarding.done.browserCookies")
        }
        /// `onboarding.done.cookieCount` — {saved} of {total} providers saved
        public static func doneCookieCount(saved: Int, total: Int) -> String {
            L10n.string("onboarding.done.cookieCount", saved, total)
        }
        /// `onboarding.done.footer` — Every one of these lives in Settings, and the assistant is one click away under Settings → System.
        public static var doneFooter: String {
            L10n.string("onboarding.done.footer")
        }
        /// `onboarding.done.intro` — That is everything the menu bar needs. Finish opens the popover with whatever quota is already readable; the rest fills in on the first refresh.
        public static var doneIntro: String {
            L10n.string("onboarding.done.intro")
        }
        /// `onboarding.done.launchAtLogin` — Launch at login
        public static var doneLaunchAtLogin: String {
            L10n.string("onboarding.done.launchAtLogin")
        }
        /// `onboarding.done.miscCount` — {count} on the Misc page
        public static func doneMiscCount(count: Int) -> String {
            L10n.string("onboarding.done.miscCount", count)
        }
        /// `onboarding.done.modelPricing` — Model pricing
        public static var doneModelPricing: String {
            L10n.string("onboarding.done.modelPricing")
        }
        /// `onboarding.done.noneShown` — None shown
        public static var doneNoneShown: String {
            L10n.string("onboarding.done.noneShown")
        }
        /// `onboarding.done.pricingBundled` — Bundled table until the first fetch
        public static var donePricingBundled: String {
            L10n.string("onboarding.done.pricingBundled")
        }
        /// `onboarding.done.pricingMerged` — Merged {when}
        public static func donePricingMerged(when: String) -> String {
            L10n.string("onboarding.done.pricingMerged", when)
        }
        /// `onboarding.done.subscriptions` — Subscriptions
        public static var doneSubscriptions: String {
            L10n.string("onboarding.done.subscriptions")
        }
        /// `onboarding.finish` — Finish
        public static var finish: String {
            L10n.string("onboarding.finish")
        }
        /// `onboarding.pricing.fetchNow` — Fetch prices now
        public static var pricingFetchNow: String {
            L10n.string("onboarding.pricing.fetchNow")
        }
        /// `onboarding.pricing.fetching` — Fetching…
        public static var pricingFetching: String {
            L10n.string("onboarding.pricing.fetching")
        }
        /// `onboarding.pricing.footer` — Prices are USD per one million tokens. Local overrides live under Settings → Model Pricing.
        public static var pricingFooter: String {
            L10n.string("onboarding.pricing.footer")
        }
        /// `onboarding.pricing.interval.hour` — hour
        public static var pricingIntervalHour: String {
            L10n.string("onboarding.pricing.interval.hour")
        }
        /// `onboarding.pricing.interval.hours` — {hours} hours
        public static func pricingIntervalHours(hours: Int) -> String {
            L10n.string("onboarding.pricing.interval.hours", hours)
        }
        /// `onboarding.pricing.intro` — Token cost is computed on this Mac from your agents' session logs, priced with a catalog merged from several public price lists — higher-priority entries win when a model appears in more than one, your own overrides beat them all, and a bundled table is the offline floor. Catalogs refresh in the background every {interval}; fetching now gives the first cost numbers current prices.
        public static func pricingIntro(interval: String) -> String {
            L10n.string("onboarding.pricing.intro", interval)
        }
        /// `onboarding.pricing.merged` — Merged {when} · {count} models
        public static func pricingMerged(when: String, count: Int) -> String {
            L10n.string("onboarding.pricing.merged", when, count)
        }
        /// `onboarding.pricing.notFetched` — Not fetched yet — the bundled table is in use.
        public static var pricingNotFetched: String {
            L10n.string("onboarding.pricing.notFetched")
        }
        /// `onboarding.pricing.source.failed` — Cached {count} · refresh failed
        public static func pricingSourceFailed(count: Int) -> String {
            L10n.string("onboarding.pricing.source.failed", count)
        }
        /// `onboarding.pricing.source.models` — {count} models
        public static func pricingSourceModels(count: Int) -> String {
            L10n.string("onboarding.pricing.source.models", count)
        }
        /// `onboarding.pricing.source.notRefreshed` — Not refreshed
        public static var pricingSourceNotRefreshed: String {
            L10n.string("onboarding.pricing.source.notRefreshed")
        }
        /// `onboarding.pricing.source.unchanged` — {count} models · unchanged
        public static func pricingSourceUnchanged(count: Int) -> String {
            L10n.string("onboarding.pricing.source.unchanged", count)
        }
        /// `onboarding.skip` — Skip for now
        public static var skip: String {
            L10n.string("onboarding.skip")
        }
        /// `onboarding.step.apiKeyProviders.subtitle` — Plans tracked with an API key or a console cookie.
        public static var stepApiKeyProvidersSubtitle: String {
            L10n.string("onboarding.step.apiKeyProviders.subtitle")
        }
        /// `onboarding.step.apiKeyProviders.title` — Other plans
        public static var stepApiKeyProvidersTitle: String {
            L10n.string("onboarding.step.apiKeyProviders.title")
        }
        /// `onboarding.step.browserCookies.subtitle` — Web quotas come from the session your browser already has.
        public static var stepBrowserCookiesSubtitle: String {
            L10n.string("onboarding.step.browserCookies.subtitle")
        }
        /// `onboarding.step.browserCookies.title` — Browser cookies
        public static var stepBrowserCookiesTitle: String {
            L10n.string("onboarding.step.browserCookies.title")
        }
        /// `onboarding.step.done.subtitle` — Everything here lives in Settings too.
        public static var stepDoneSubtitle: String {
            L10n.string("onboarding.step.done.subtitle")
        }
        /// `onboarding.step.done.title` — All set
        public static var stepDoneTitle: String {
            L10n.string("onboarding.step.done.title")
        }
        /// `onboarding.step.pricing.subtitle` — Where the token prices behind the cost numbers come from.
        public static var stepPricingSubtitle: String {
            L10n.string("onboarding.step.pricing.subtitle")
        }
        /// `onboarding.step.pricing.title` — Model pricing
        public static var stepPricingTitle: String {
            L10n.string("onboarding.step.pricing.title")
        }
        /// `onboarding.step.subscriptions.subtitle` — Turn on the plans you pay for.
        public static var stepSubscriptionsSubtitle: String {
            L10n.string("onboarding.step.subscriptions.subtitle")
        }
        /// `onboarding.step.subscriptions.title` — Subscriptions
        public static var stepSubscriptionsTitle: String {
            L10n.string("onboarding.step.subscriptions.title")
        }
        /// `onboarding.step.welcome.subtitle` — What Vibe Bar does, in one paragraph.
        public static var stepWelcomeSubtitle: String {
            L10n.string("onboarding.step.welcome.subtitle")
        }
        /// `onboarding.step.welcome.title` — Welcome
        public static var stepWelcomeTitle: String {
            L10n.string("onboarding.step.welcome.title")
        }
        /// `onboarding.subscriptions.claude.detected` — Claude Code login detected — quota will come from it.
        public static var subscriptionsClaudeDetected: String {
            L10n.string("onboarding.subscriptions.claude.detected")
        }
        /// `onboarding.subscriptions.claude.missing` — No Claude Code login found. Run `claude login`, or import claude.ai cookies from your browser below.
        public static var subscriptionsClaudeMissing: String {
            L10n.string("onboarding.subscriptions.claude.missing")
        }
        /// `onboarding.subscriptions.claude.web` — claude.ai cookies saved — quota will come from them.
        public static var subscriptionsClaudeWeb: String {
            L10n.string("onboarding.subscriptions.claude.web")
        }
        /// `onboarding.subscriptions.codex.detected` — Codex CLI login detected — quota will come from it.
        public static var subscriptionsCodexDetected: String {
            L10n.string("onboarding.subscriptions.codex.detected")
        }
        /// `onboarding.subscriptions.codex.missing` — No Codex CLI login found. Run `codex login`, or import ChatGPT cookies from your browser below.
        public static var subscriptionsCodexMissing: String {
            L10n.string("onboarding.subscriptions.codex.missing")
        }
        /// `onboarding.subscriptions.codex.web` — ChatGPT web cookies saved — quota will come from them.
        public static var subscriptionsCodexWeb: String {
            L10n.string("onboarding.subscriptions.codex.web")
        }
        /// `onboarding.subscriptions.gemini.hint` — Gemini quota is read from gemini.google.com cookies; there is no CLI login or WebView path. AntiGravity is probed locally when it is running.
        public static var subscriptionsGeminiHint: String {
            L10n.string("onboarding.subscriptions.gemini.hint")
        }
        /// `onboarding.subscriptions.grok.detected` — ~/.grok/auth.json detected — quota will come from it.
        public static var subscriptionsGrokDetected: String {
            L10n.string("onboarding.subscriptions.grok.detected")
        }
        /// `onboarding.subscriptions.grok.missing` — No ~/.grok/auth.json yet. Run `grok login`, or import grok.com cookies from your browser below.
        public static var subscriptionsGrokMissing: String {
            L10n.string("onboarding.subscriptions.grok.missing")
        }
        /// `onboarding.subscriptions.intro` — Turn on the subscriptions you use. A provider that is off stays out of the Overview and the menu bar; turning one off later keeps its credentials and history.
        public static var subscriptionsIntro: String {
            L10n.string("onboarding.subscriptions.intro")
        }
        /// `onboarding.subscriptions.productLine.claude` — Claude Code · claude.ai web
        public static var subscriptionsProductLineClaude: String {
            L10n.string("onboarding.subscriptions.productLine.claude")
        }
        /// `onboarding.subscriptions.productLine.codex` — Codex CLI · ChatGPT web
        public static var subscriptionsProductLineCodex: String {
            L10n.string("onboarding.subscriptions.productLine.codex")
        }
        /// `onboarding.subscriptions.productLine.gemini` — Gemini web · AntiGravity
        public static var subscriptionsProductLineGemini: String {
            L10n.string("onboarding.subscriptions.productLine.gemini")
        }
        /// `onboarding.subscriptions.productLine.grok` — Grok CLI · grok.com · Cursor
        public static var subscriptionsProductLineGrok: String {
            L10n.string("onboarding.subscriptions.productLine.grok")
        }
        /// `onboarding.subscriptions.showInOverview` — Show in Overview
        public static var subscriptionsShowInOverview: String {
            L10n.string("onboarding.subscriptions.showInOverview")
        }
        /// `onboarding.title` — Setup
        public static var title: String {
            L10n.string("onboarding.title")
        }
        /// `onboarding.welcome.cost.detail` — Priced locally from the agents' own session logs against a merged model price catalog.
        public static var welcomeCostDetail: String {
            L10n.string("onboarding.welcome.cost.detail")
        }
        /// `onboarding.welcome.cost.title` — Token cost
        public static var welcomeCostTitle: String {
            L10n.string("onboarding.welcome.cost.title")
        }
        /// `onboarding.welcome.footer` — This takes about two minutes. Every choice here can be changed later in Settings, and the assistant is one click away under Settings → System.
        public static var welcomeFooter: String {
            L10n.string("onboarding.welcome.footer")
        }
        /// `onboarding.welcome.intro` — Vibe Bar sits in your menu bar and shows, at a glance, how much of each AI subscription you have left, what your coding agents are spending, and which sessions and skills live on this Mac. It reads the credentials the Codex, Claude Code, Gemini and Grok CLIs already keep here, adds web quotas from your browser's cookies when you ask it to, and never sends any of it anywhere but the provider it came from.
        public static var welcomeIntro: String {
            L10n.string("onboarding.welcome.intro")
        }
        /// `onboarding.welcome.mcp.detail` — Your agents can ask Vibe Bar for quota and cost over a Unix socket in your home directory.
        public static var welcomeMcpDetail: String {
            L10n.string("onboarding.welcome.mcp.detail")
        }
        /// `onboarding.welcome.mcp.title` — Local MCP server
        public static var welcomeMcpTitle: String {
            L10n.string("onboarding.welcome.mcp.title")
        }
        /// `onboarding.welcome.quotas.detail` — Codex, Claude Code, Gemini, Grok and a shelf of API-key plans, each with its reset countdown.
        public static var welcomeQuotasDetail: String {
            L10n.string("onboarding.welcome.quotas.detail")
        }
        /// `onboarding.welcome.quotas.title` — Subscription quotas
        public static var welcomeQuotasTitle: String {
            L10n.string("onboarding.welcome.quotas.title")
        }
        /// `onboarding.welcome.sessions.detail` — Browse, search and tidy agent sessions and shared skills from the Workbench.
        public static var welcomeSessionsDetail: String {
            L10n.string("onboarding.welcome.sessions.detail")
        }
        /// `onboarding.welcome.sessions.title` — Sessions and skills
        public static var welcomeSessionsTitle: String {
            L10n.string("onboarding.welcome.sessions.title")
        }
    }

    public enum Platform {
        /// `platform.macos.launchAtLogin.detail` — Vibe Bar is a menu-bar app with no Dock icon. Starting it at login keeps the quota readout and the local MCP server available from the moment you sign in; macOS may ask you to approve the login item in System Settings the first time.
        public static var macosLaunchAtLoginDetail: String {
            L10n.string("platform.macos.launchAtLogin.detail")
        }
        /// `platform.macos.launchAtLogin.enabled` — Enabled in macOS Login Items.
        public static var macosLaunchAtLoginEnabled: String {
            L10n.string("platform.macos.launchAtLogin.enabled")
        }
        /// `platform.macos.launchAtLogin.off` — Off.
        public static var macosLaunchAtLoginOff: String {
            L10n.string("platform.macos.launchAtLogin.off")
        }
        /// `platform.macos.launchAtLogin.subtitle` — Keep the readout in your menu bar from the moment you sign in.
        public static var macosLaunchAtLoginSubtitle: String {
            L10n.string("platform.macos.launchAtLogin.subtitle")
        }
        /// `platform.macos.launchAtLogin.title` — Launch at login
        public static var macosLaunchAtLoginTitle: String {
            L10n.string("platform.macos.launchAtLogin.title")
        }
        /// `platform.macos.launchAtLogin.toggle` — Launch Vibe Bar at login
        public static var macosLaunchAtLoginToggle: String {
            L10n.string("platform.macos.launchAtLogin.toggle")
        }
    }

    public enum Popover {
        /// `popover.header.machinesSubtitle` — End-to-end encrypted remote usage
        public static var headerMachinesSubtitle: String {
            L10n.string("popover.header.machinesSubtitle")
        }
        /// `popover.header.miscSubtitle` — Usage-only · sign in or paste a key
        public static var headerMiscSubtitle: String {
            L10n.string("popover.header.miscSubtitle")
        }
        /// `popover.header.overviewSubtitle` — All providers · quota & cost
        public static var headerOverviewSubtitle: String {
            L10n.string("popover.header.overviewSubtitle")
        }
        /// `popover.refreshGoogleAI` — Refresh Gemini Web + AntiGravity
        public static var refreshGoogleAI: String {
            L10n.string("popover.refreshGoogleAI")
        }
        /// `popover.refreshSpaceXAI` — Refresh Grok + Cursor
        public static var refreshSpaceXAI: String {
            L10n.string("popover.refreshSpaceXAI")
        }
        /// `popover.showPage` — Show {page}
        public static func showPage(page: String) -> String {
            L10n.string("popover.showPage", page)
        }
        /// `popover.tab.machines` — Machines
        public static var tabMachines: String {
            L10n.string("popover.tab.machines")
        }
        /// `popover.tab.misc` — Misc Providers
        public static var tabMisc: String {
            L10n.string("popover.tab.misc")
        }
        /// `popover.tab.miscShort` — Misc
        public static var tabMiscShort: String {
            L10n.string("popover.tab.miscShort")
        }
        /// `popover.tab.overview` — Overview
        public static var tabOverview: String {
            L10n.string("popover.tab.overview")
        }
    }

    public enum Quota {
        /// `quota.bucket.noResetInfo` — No reset info
        public static var bucketNoResetInfo: String {
            L10n.string("quota.bucket.noResetInfo")
        }
        /// `quota.bucket.resetsIn` — Resets in {when}
        public static func bucketResetsIn(when: String) -> String {
            L10n.string("quota.bucket.resetsIn", when)
        }
        /// `quota.empty.needsLogin.detail` — Run `{command} login` in your terminal, then refresh.
        public static func emptyNeedsLoginDetail(command: String) -> String {
            L10n.string("quota.empty.needsLogin.detail", command)
        }
        /// `quota.empty.needsLogin.headline` — Needs re-login
        public static var emptyNeedsLoginHeadline: String {
            L10n.string("quota.empty.needsLogin.headline")
        }
        /// `quota.empty.network.detail` — Couldn't reach the official API. Check your internet connection and try again.
        public static var emptyNetworkDetail: String {
            L10n.string("quota.empty.network.detail")
        }
        /// `quota.empty.network.headline` — Network error
        public static var emptyNetworkHeadline: String {
            L10n.string("quota.empty.network.headline")
        }
        /// `quota.empty.noAccount.detail` — Log in with the official CLI on this Mac, then refresh.
        public static var emptyNoAccountDetail: String {
            L10n.string("quota.empty.noAccount.detail")
        }
        /// `quota.empty.noAccount.headline` — No account found
        public static var emptyNoAccountHeadline: String {
            L10n.string("quota.empty.noAccount.headline")
        }
        /// `quota.empty.parseChanged.detail` — The official API returned an unexpected shape. Try refreshing or update Vibe Bar.
        public static var emptyParseChangedDetail: String {
            L10n.string("quota.empty.parseChanged.detail")
        }
        /// `quota.empty.parseChanged.headline` — Response format changed
        public static var emptyParseChangedHeadline: String {
            L10n.string("quota.empty.parseChanged.headline")
        }
        /// `quota.empty.rateLimited.detail` — The official API is asking us to wait. Try again in a moment.
        public static var emptyRateLimitedDetail: String {
            L10n.string("quota.empty.rateLimited.detail")
        }
        /// `quota.empty.rateLimited.headline` — Rate limited
        public static var emptyRateLimitedHeadline: String {
            L10n.string("quota.empty.rateLimited.headline")
        }
        /// `quota.forecast.confidence.high` — High confidence
        public static var forecastConfidenceHigh: String {
            L10n.string("quota.forecast.confidence.high")
        }
        /// `quota.forecast.confidence.learning` — Learning
        public static var forecastConfidenceLearning: String {
            L10n.string("quota.forecast.confidence.learning")
        }
        /// `quota.forecast.confidence.medium` — Medium confidence
        public static var forecastConfidenceMedium: String {
            L10n.string("quota.forecast.confidence.medium")
        }
        /// `quota.forecast.guidance.atRisk` — Slow down or shift work to another quota
        public static var forecastGuidanceAtRisk: String {
            L10n.string("quota.forecast.guidance.atRisk")
        }
        /// `quota.forecast.guidance.available` — Target {target}% left · about {unused}% available
        public static func forecastGuidanceAvailable(target: Int, unused: Int) -> String {
            L10n.string("quota.forecast.guidance.available", target, unused)
        }
        /// `quota.forecast.guidance.surplus` — About {unused}% likely unused beyond the {target}% safety target
        public static func forecastGuidanceSurplus(unused: Int, target: Int) -> String {
            L10n.string("quota.forecast.guidance.surplus", unused, target)
        }
        /// `quota.forecast.guidance.usedAvailable` — Target {target}% used · about {unused}% capacity available
        public static func forecastGuidanceUsedAvailable(target: Int, unused: Int) -> String {
            L10n.string("quota.forecast.guidance.usedAvailable", target, unused)
        }
        /// `quota.forecast.guidance.usedSurplus` — About {unused}% capacity may remain beyond the {target}% used target
        public static func forecastGuidanceUsedSurplus(unused: Int, target: Int) -> String {
            L10n.string("quota.forecast.guidance.usedSurplus", unused, target)
        }
        /// `quota.forecast.guidance.usedWithinTarget` — Within the {target}% used target
        public static func forecastGuidanceUsedWithinTarget(target: Int) -> String {
            L10n.string("quota.forecast.guidance.usedWithinTarget", target)
        }
        /// `quota.forecast.guidance.watch` — Recent usage is above the safe range
        public static var forecastGuidanceWatch: String {
            L10n.string("quota.forecast.guidance.watch")
        }
        /// `quota.forecast.guidance.withinTarget` — Within the {target}% safety target
        public static func forecastGuidanceWithinTarget(target: Int) -> String {
            L10n.string("quota.forecast.guidance.withinTarget", target)
        }
        /// `quota.forecast.reset.atRisk` — Likely to run out before reset
        public static var forecastResetAtRisk: String {
            L10n.string("quota.forecast.reset.atRisk")
        }
        /// `quota.forecast.reset.enough` — Forecast {remaining}% left at reset
        public static func forecastResetEnough(remaining: Int) -> String {
            L10n.string("quota.forecast.reset.enough", remaining)
        }
        /// `quota.forecast.reset.learning` — Learning your pattern · about {remaining}% left
        public static func forecastResetLearning(remaining: Int) -> String {
            L10n.string("quota.forecast.reset.learning", remaining)
        }
        /// `quota.forecast.reset.surplus` — Likely surplus · forecast {remaining}% left
        public static func forecastResetSurplus(remaining: Int) -> String {
            L10n.string("quota.forecast.reset.surplus", remaining)
        }
        /// `quota.forecast.reset.watch` — May run short · forecast {remaining}% left
        public static func forecastResetWatch(remaining: Int) -> String {
            L10n.string("quota.forecast.reset.watch", remaining)
        }
        /// `quota.forecast.status.atRisk` — At risk · likely to run out before reset
        public static var forecastStatusAtRisk: String {
            L10n.string("quota.forecast.status.atRisk")
        }
        /// `quota.forecast.status.enough` — Enough · forecast {value} at reset
        public static func forecastStatusEnough(value: String) -> String {
            L10n.string("quota.forecast.status.enough", value)
        }
        /// `quota.forecast.status.learning` — Learning · about {value} at reset
        public static func forecastStatusLearning(value: String) -> String {
            L10n.string("quota.forecast.status.learning", value)
        }
        /// `quota.forecast.status.surplus` — Surplus · forecast {value} at reset
        public static func forecastStatusSurplus(value: String) -> String {
            L10n.string("quota.forecast.status.surplus", value)
        }
        /// `quota.forecast.status.watch` — Watch · forecast {value} at reset
        public static func forecastStatusWatch(value: String) -> String {
            L10n.string("quota.forecast.status.watch", value)
        }
        /// `quota.forecast.useUp.beforeReset` — Expected to run out before reset
        public static var forecastUseUpBeforeReset: String {
            L10n.string("quota.forecast.useUp.beforeReset")
        }
        /// `quota.forecast.useUp.couldRunOut` — Could run out in {countdown}
        public static func forecastUseUpCouldRunOut(countdown: String) -> String {
            L10n.string("quota.forecast.useUp.couldRunOut", countdown)
        }
        /// `quota.forecast.useUp.estimated` — Estimated to run out in {countdown}
        public static func forecastUseUpEstimated(countdown: String) -> String {
            L10n.string("quota.forecast.useUp.estimated", countdown)
        }
        /// `quota.forecast.useUp.lastsUntilReset` — Projected to last until reset
        public static var forecastUseUpLastsUntilReset: String {
            L10n.string("quota.forecast.useUp.lastsUntilReset")
        }
        /// `quota.forecast.useUp.uncertain` — Use-up time uncertain · may run short before reset
        public static var forecastUseUpUncertain: String {
            L10n.string("quota.forecast.useUp.uncertain")
        }
        /// `quota.forecast.value.left` — {percent}% left
        public static func forecastValueLeft(percent: Int) -> String {
            L10n.string("quota.forecast.value.left", percent)
        }
        /// `quota.forecast.value.used` — {percent}% used
        public static func forecastValueUsed(percent: Int) -> String {
            L10n.string("quota.forecast.value.used", percent)
        }
        /// `quota.forecast.verdict.atRisk` — At risk
        public static var forecastVerdictAtRisk: String {
            L10n.string("quota.forecast.verdict.atRisk")
        }
        /// `quota.forecast.verdict.enough` — Enough
        public static var forecastVerdictEnough: String {
            L10n.string("quota.forecast.verdict.enough")
        }
        /// `quota.forecast.verdict.learning` — Learning
        public static var forecastVerdictLearning: String {
            L10n.string("quota.forecast.verdict.learning")
        }
        /// `quota.forecast.verdict.surplus` — Surplus
        public static var forecastVerdictSurplus: String {
            L10n.string("quota.forecast.verdict.surplus")
        }
        /// `quota.forecast.verdict.watch` — Watch
        public static var forecastVerdictWatch: String {
            L10n.string("quota.forecast.verdict.watch")
        }
        /// `quota.freshness.age.days` — {days}d
        public static func freshnessAgeDays(days: Int) -> String {
            L10n.string("quota.freshness.age.days", days)
        }
        /// `quota.freshness.age.hours` — {hours}h
        public static func freshnessAgeHours(hours: Int) -> String {
            L10n.string("quota.freshness.age.hours", hours)
        }
        /// `quota.freshness.age.minutes` — {minutes}m
        public static func freshnessAgeMinutes(minutes: Int) -> String {
            L10n.string("quota.freshness.age.minutes", minutes)
        }
        /// `quota.freshness.age.seconds` — {seconds}s
        public static func freshnessAgeSeconds(seconds: Int) -> String {
            L10n.string("quota.freshness.age.seconds", seconds)
        }
        /// `quota.freshness.dataAge` — data {age} old
        public static func freshnessDataAge(age: String) -> String {
            L10n.string("quota.freshness.dataAge", age)
        }
        /// `quota.freshness.defaultHelp` — Live quota has not refreshed within the expected interval.
        public static var freshnessDefaultHelp: String {
            L10n.string("quota.freshness.defaultHelp")
        }
        /// `quota.freshness.line` — {attempt} · {data} · {reason}
        public static func freshnessLine(attempt: String, data: String, reason: String) -> String {
            L10n.string("quota.freshness.line", attempt, data, reason)
        }
        /// `quota.freshness.noCachedData` — no cached data
        public static var freshnessNoCachedData: String {
            L10n.string("quota.freshness.noCachedData")
        }
        /// `quota.freshness.refreshFailed` — Refresh failed
        public static var freshnessRefreshFailed: String {
            L10n.string("quota.freshness.refreshFailed")
        }
        /// `quota.freshness.refreshFailedAgo` — Refresh failed {age} ago
        public static func freshnessRefreshFailedAgo(age: String) -> String {
            L10n.string("quota.freshness.refreshFailedAgo", age)
        }
        /// `quota.freshness.staleNeverUpdated` — Stale · never updated
        public static var freshnessStaleNeverUpdated: String {
            L10n.string("quota.freshness.staleNeverUpdated")
        }
        /// `quota.freshness.staleUpdatedAgo` — Stale · updated {age} ago
        public static func freshnessStaleUpdatedAgo(age: String) -> String {
            L10n.string("quota.freshness.staleUpdatedAgo", age)
        }
        /// `quota.group.allModels` — All Models
        public static var groupAllModels: String {
            L10n.string("quota.group.allModels")
        }
        /// `quota.group.daily` — Daily
        public static var groupDaily: String {
            L10n.string("quota.group.daily")
        }
        /// `quota.group.fiveHours` — 5 Hours
        public static var groupFiveHours: String {
            L10n.string("quota.group.fiveHours")
        }
        /// `quota.group.monthly` — Monthly
        public static var groupMonthly: String {
            L10n.string("quota.group.monthly")
        }
        /// `quota.group.noUtilization` — No utilization data — try refreshing.
        public static var groupNoUtilization: String {
            L10n.string("quota.group.noUtilization")
        }
        /// `quota.group.other` — Other
        public static var groupOther: String {
            L10n.string("quota.group.other")
        }
        /// `quota.group.otherModels` — Other Models
        public static var groupOtherModels: String {
            L10n.string("quota.group.otherModels")
        }
        /// `quota.group.weekly` — Weekly
        public static var groupWeekly: String {
            L10n.string("quota.group.weekly")
        }
        /// `quota.group.weeklyCredits` — Weekly Credits
        public static var groupWeeklyCredits: String {
            L10n.string("quota.group.weeklyCredits")
        }
        /// `quota.login.claude` — Run claude login, then refresh.
        public static var loginClaude: String {
            L10n.string("quota.login.claude")
        }
        /// `quota.login.codex` — Run codex login, then refresh.
        public static var loginCodex: String {
            L10n.string("quota.login.codex")
        }
        /// `quota.login.cursor` — Sign in to Cursor.app or import cursor.com cookies, then refresh.
        public static var loginCursor: String {
            L10n.string("quota.login.cursor")
        }
        /// `quota.login.grok` — Run grok login or import grok.com cookies, then refresh.
        public static var loginGrok: String {
            L10n.string("quota.login.grok")
        }
        /// `quota.login.misc` — Configure {provider} in Settings → Misc Providers.
        public static func loginMisc(provider: String) -> String {
            L10n.string("quota.login.misc", provider)
        }
        /// `quota.mode.remaining` — remaining
        public static var modeRemaining: String {
            L10n.string("quota.mode.remaining")
        }
        /// `quota.mode.used` — used
        public static var modeUsed: String {
            L10n.string("quota.mode.used")
        }
        /// `quota.pace.lastsUntilReset` — Lasts until reset
        public static var paceLastsUntilReset: String {
            L10n.string("quota.pace.lastsUntilReset")
        }
        /// `quota.pace.runsOutIn` — Runs out in {countdown}
        public static func paceRunsOutIn(countdown: String) -> String {
            L10n.string("quota.pace.runsOutIn", countdown)
        }
        /// `quota.perModelLimits` — {count, plural, one {1 per-model limit} other {# per-model limits}} · open {provider} for details
        public static func perModelLimits(count: Int, provider: String) -> String {
            L10n.string("quota.perModelLimits", count, provider)
        }
        /// `quota.reset.in` — resets in {duration}
        public static func resetIn(duration: String) -> String {
            L10n.string("quota.reset.in", duration)
        }
        /// `quota.reset.passed` — reset passed
        public static var resetPassed: String {
            L10n.string("quota.reset.passed")
        }
        /// `quota.reset.passedAt` — reset passed · {time}
        public static func resetPassedAt(time: String) -> String {
            L10n.string("quota.reset.passedAt", time)
        }
        /// `quota.resetCredits.available` — {count, plural, one {1 manual reset available} other {# manual resets available}}
        public static func resetCreditsAvailable(count: Int) -> String {
            L10n.string("quota.resetCredits.available", count)
        }
        /// `quota.resetCredits.availableWithExpiry` — {available} · next expires in {countdown}
        public static func resetCreditsAvailableWithExpiry(available: String, countdown: String) -> String {
            L10n.string("quota.resetCredits.availableWithExpiry", available, countdown)
        }
        /// `quota.resetCredits.count` — {count}
        public static func resetCreditsCount(count: Int) -> String {
            L10n.string("quota.resetCredits.count", count)
        }
        /// `quota.resetCredits.title` — Limit reset credits
        public static var resetCreditsTitle: String {
            L10n.string("quota.resetCredits.title")
        }
        /// `quota.resetHistory.a11y.empty` — Reset history comparison. {verdict}
        public static func resetHistoryA11yEmpty(verdict: String) -> String {
            L10n.string("quota.resetHistory.a11y.empty", verdict)
        }
        /// `quota.resetHistory.a11y.more` —  And {count} more quotas.
        public static func resetHistoryA11yMore(count: Int) -> String {
            L10n.string("quota.resetHistory.a11y.more", count)
        }
        /// `quota.resetHistory.a11y.summary` — Reset history comparison, {window}, bar height is the quota remaining at reset.{truncation} {headline}. {verdict} {lanes}.{more}
        public static func resetHistoryA11ySummary(window: String, truncation: String, headline: String, verdict: String, lanes: String, more: String) -> String {
            L10n.string("quota.resetHistory.a11y.summary", window, truncation, headline, verdict, lanes, more)
        }
        /// `quota.resetHistory.a11y.truncation` —  Grid {note}; the figures cover every one.
        public static func resetHistoryA11yTruncation(note: String) -> String {
            L10n.string("quota.resetHistory.a11y.truncation", note)
        }
        /// `quota.resetHistory.axis.cycle` — Cycles
        public static var resetHistoryAxisCycle: String {
            L10n.string("quota.resetHistory.axis.cycle")
        }
        /// `quota.resetHistory.axis.cycleHelp` — One column per cycle, newest aligned across every quota
        public static var resetHistoryAxisCycleHelp: String {
            L10n.string("quota.resetHistory.axis.cycleHelp")
        }
        /// `quota.resetHistory.axis.time` — Time
        public static var resetHistoryAxisTime: String {
            L10n.string("quota.resetHistory.axis.time")
        }
        /// `quota.resetHistory.axis.timeHelp` — Each cycle where it actually happened, on a shared calendar
        public static var resetHistoryAxisTimeHelp: String {
            L10n.string("quota.resetHistory.axis.timeHelp")
        }
        /// `quota.resetHistory.axisCyclesBack` — −{count}
        public static func resetHistoryAxisCyclesBack(count: Int) -> String {
            L10n.string("quota.resetHistory.axisCyclesBack", count)
        }
        /// `quota.resetHistory.axisNow` — now
        public static var resetHistoryAxisNow: String {
            L10n.string("quota.resetHistory.axisNow")
        }
        /// `quota.resetHistory.lane.emptyState` — No completed cycles yet — a cycle is recorded when the quota refills
        public static var resetHistoryLaneEmptyState: String {
            L10n.string("quota.resetHistory.lane.emptyState")
        }
        /// `quota.resetHistory.lane.noCycles` — No completed cycles yet
        public static var resetHistoryLaneNoCycles: String {
            L10n.string("quota.resetHistory.lane.noCycles")
        }
        /// `quota.resetHistory.lane.spokenNoCycles` — {label}: no completed cycles
        public static func resetHistoryLaneSpokenNoCycles(label: String) -> String {
            L10n.string("quota.resetHistory.lane.spokenNoCycles", label)
        }
        /// `quota.resetHistory.lane.spokenWaste` — {label}: {percent}% wasted on average over {count} cycles
        public static func resetHistoryLaneSpokenWaste(label: String, percent: String, count: Int) -> String {
            L10n.string("quota.resetHistory.lane.spokenWaste", label, percent, count)
        }
        /// `quota.resetHistory.lane.wasteSummary` — avg wasted {percent}% · last {count, plural, one {1 cycle} other {# cycles}}
        public static func resetHistoryLaneWasteSummary(percent: String, count: Int) -> String {
            L10n.string("quota.resetHistory.lane.wasteSummary", percent, count)
        }
        /// `quota.resetHistory.reset.earlyClockRestarted` — refilled early, next window restarted
        public static var resetHistoryResetEarlyClockRestarted: String {
            L10n.string("quota.resetHistory.reset.earlyClockRestarted")
        }
        /// `quota.resetHistory.reset.earlyClockUnchanged` — refilled early, next reset unchanged
        public static var resetHistoryResetEarlyClockUnchanged: String {
            L10n.string("quota.resetHistory.reset.earlyClockUnchanged")
        }
        /// `quota.resetHistory.reset.earlyUnclear` — refilled early, onto a different schedule
        public static var resetHistoryResetEarlyUnclear: String {
            L10n.string("quota.resetHistory.reset.earlyUnclear")
        }
        /// `quota.resetHistory.spoken.allCycles` — every recorded cycle
        public static var resetHistorySpokenAllCycles: String {
            L10n.string("quota.resetHistory.spoken.allCycles")
        }
        /// `quota.resetHistory.spoken.allTime` — all recorded history
        public static var resetHistorySpokenAllTime: String {
            L10n.string("quota.resetHistory.spoken.allTime")
        }
        /// `quota.resetHistory.spoken.eightCycles` — last 8 cycles
        public static var resetHistorySpokenEightCycles: String {
            L10n.string("quota.resetHistory.spoken.eightCycles")
        }
        /// `quota.resetHistory.spoken.eightWeeks` — last 8 weeks
        public static var resetHistorySpokenEightWeeks: String {
            L10n.string("quota.resetHistory.spoken.eightWeeks")
        }
        /// `quota.resetHistory.spoken.fourCycles` — last 4 cycles
        public static var resetHistorySpokenFourCycles: String {
            L10n.string("quota.resetHistory.spoken.fourCycles")
        }
        /// `quota.resetHistory.spoken.fourWeeks` — last 4 weeks
        public static var resetHistorySpokenFourWeeks: String {
            L10n.string("quota.resetHistory.spoken.fourWeeks")
        }
        /// `quota.resetHistory.spoken.twelveCycles` — last 12 cycles
        public static var resetHistorySpokenTwelveCycles: String {
            L10n.string("quota.resetHistory.spoken.twelveCycles")
        }
        /// `quota.resetHistory.spoken.twelveWeeks` — last 12 weeks
        public static var resetHistorySpokenTwelveWeeks: String {
            L10n.string("quota.resetHistory.spoken.twelveWeeks")
        }
        /// `quota.resetHistory.title` — Reset History
        public static var resetHistoryTitle: String {
            L10n.string("quota.resetHistory.title")
        }
        /// `quota.resetHistory.totals.headline` — {used}% used · {wasted}% wasted · {count, plural, one {1 cycle} other {# cycles}}
        public static func resetHistoryTotalsHeadline(used: String, wasted: String, count: Int) -> String {
            L10n.string("quota.resetHistory.totals.headline", used, wasted, count)
        }
        /// `quota.resetHistory.totals.none` — No completed cycles in this window
        public static var resetHistoryTotalsNone: String {
            L10n.string("quota.resetHistory.totals.none")
        }
        /// `quota.resetHistory.truncation` — showing the newest {shown} of {total} cycles
        public static func resetHistoryTruncation(shown: Int, total: Int) -> String {
            L10n.string("quota.resetHistory.truncation", shown, total)
        }
        /// `quota.resetHistory.verdict.clean` — Nothing is going noticeably to waste — {percent}% of the refilled capacity was spent.
        public static func resetHistoryVerdictClean(percent: String) -> String {
            L10n.string("quota.resetHistory.verdict.clean", percent)
        }
        /// `quota.resetHistory.verdict.leaky` — {label} left {percent}% unused on average across {count, plural, one {1 cycle} other {# cycles}}.
        public static func resetHistoryVerdictLeaky(label: String, percent: String, count: Int) -> String {
            L10n.string("quota.resetHistory.verdict.leaky", label, percent, count)
        }
        /// `quota.resetHistory.verdict.noCycles` — No completed cycles yet — a cycle is recorded when a quota refills.
        public static var resetHistoryVerdictNoCycles: String {
            L10n.string("quota.resetHistory.verdict.noCycles")
        }
        /// `quota.resetHistory.verdict.noQuota` — No weekly or longer quota is being tracked yet.
        public static var resetHistoryVerdictNoQuota: String {
            L10n.string("quota.resetHistory.verdict.noQuota")
        }
        /// `quota.resetHistory.verdict.wasteful` — {label} refilled {count, plural, one {once} other {# times}} with more than half unused.
        public static func resetHistoryVerdictWasteful(label: String, count: Int) -> String {
            L10n.string("quota.resetHistory.verdict.wasteful", label, count)
        }
        /// `quota.resetHistory.window.all` — All
        public static var resetHistoryWindowAll: String {
            L10n.string("quota.resetHistory.window.all")
        }
        /// `quota.resetHistory.window.eightWeeks` — 8w
        public static var resetHistoryWindowEightWeeks: String {
            L10n.string("quota.resetHistory.window.eightWeeks")
        }
        /// `quota.resetHistory.window.fourWeeks` — 4w
        public static var resetHistoryWindowFourWeeks: String {
            L10n.string("quota.resetHistory.window.fourWeeks")
        }
        /// `quota.resetHistory.window.twelveWeeks` — 12w
        public static var resetHistoryWindowTwelveWeeks: String {
            L10n.string("quota.resetHistory.window.twelveWeeks")
        }
        /// `quota.upcoming.axisDays` — +{days}d
        public static func upcomingAxisDays(days: Int) -> String {
            L10n.string("quota.upcoming.axisDays", days)
        }
        /// `quota.upcoming.axisHours` — +{hours}h
        public static func upcomingAxisHours(hours: Int) -> String {
            L10n.string("quota.upcoming.axisHours", hours)
        }
        /// `quota.upcoming.empty` — Nothing refills in the next seven days.
        public static var upcomingEmpty: String {
            L10n.string("quota.upcoming.empty")
        }
        /// `quota.upcoming.forecastAtReset` — forecast {percent}% left at reset
        public static func upcomingForecastAtReset(percent: Int) -> String {
            L10n.string("quota.upcoming.forecastAtReset", percent)
        }
        /// `quota.upcoming.gain` — +{gain}%
        public static func upcomingGain(gain: Int) -> String {
            L10n.string("quota.upcoming.gain", gain)
        }
        /// `quota.upcoming.horizon` — next 7 days
        public static var upcomingHorizon: String {
            L10n.string("quota.upcoming.horizon")
        }
        /// `quota.upcoming.leftAndGain` — {remaining}% left now · +{gain}% comes back
        public static func upcomingLeftAndGain(remaining: Int, gain: Int) -> String {
            L10n.string("quota.upcoming.leftAndGain", remaining, gain)
        }
        /// `quota.upcoming.markerHelp` — {label} — {remaining}% now, +{gain}% {countdown}
        public static func upcomingMarkerHelp(label: String, remaining: Int, gain: Int, countdown: String) -> String {
            L10n.string("quota.upcoming.markerHelp", label, remaining, gain, countdown)
        }
        /// `quota.upcoming.resetsAt` — resets {countdown} · {absolute}
        public static func upcomingResetsAt(countdown: String, absolute: String) -> String {
            L10n.string("quota.upcoming.resetsAt", countdown, absolute)
        }
        /// `quota.upcoming.title` — Upcoming Resets
        public static var upcomingTitle: String {
            L10n.string("quota.upcoming.title")
        }
        /// `quota.update.failed` — Update failed: {reason}
        public static func updateFailed(reason: String) -> String {
            L10n.string("quota.update.failed", reason)
        }
    }

    public enum Settings {
        /// `settings.language.caption` — Vibe Bar follows the macOS language unless you pick one here. Provider, model and harness names stay as their owners spell them.
        public static var languageCaption: String {
            L10n.string("settings.language.caption")
        }
        /// `settings.language.system` — System
        public static var languageSystem: String {
            L10n.string("settings.language.system")
        }
        /// `settings.language.title` — Language
        public static var languageTitle: String {
            L10n.string("settings.language.title")
        }
    }

    public enum Status {
        /// `status.card.componentCount` — {count, plural, one {1 component} other {# components}}
        public static func cardComponentCount(count: Int) -> String {
            L10n.string("status.card.componentCount", count)
        }
        /// `status.card.components` — Components
        public static var cardComponents: String {
            L10n.string("status.card.components")
        }
        /// `status.card.noIncidents` — No incidents in the last 90 days
        public static var cardNoIncidents: String {
            L10n.string("status.card.noIncidents")
        }
        /// `status.card.openIncident` — Open incident
        public static var cardOpenIncident: String {
            L10n.string("status.card.openIncident")
        }
        /// `status.card.openStatusPage` — Open {host}
        public static func cardOpenStatusPage(host: String) -> String {
            L10n.string("status.card.openStatusPage", host)
        }
        /// `status.card.refresh` — Refresh service status
        public static var cardRefresh: String {
            L10n.string("status.card.refresh")
        }
        /// `status.card.statusPageFallback` — status page
        public static var cardStatusPageFallback: String {
            L10n.string("status.card.statusPageFallback")
        }
        /// `status.card.title` — Service Status
        public static var cardTitle: String {
            L10n.string("status.card.title")
        }
        /// `status.card.updatedHoursAgo` — updated {hours}h ago
        public static func cardUpdatedHoursAgo(hours: Int) -> String {
            L10n.string("status.card.updatedHoursAgo", hours)
        }
        /// `status.card.updatedJustNow` — updated just now
        public static var cardUpdatedJustNow: String {
            L10n.string("status.card.updatedJustNow")
        }
        /// `status.card.updatedMinutesAgo` — updated {minutes}m ago
        public static func cardUpdatedMinutesAgo(minutes: Int) -> String {
            L10n.string("status.card.updatedMinutesAgo", minutes)
        }
        /// `status.card.uptime` — {percent} uptime
        public static func cardUptime(percent: String) -> String {
            L10n.string("status.card.uptime", percent)
        }
        /// `status.card.uptimeStrip` — Service uptime over the last {days} days
        public static func cardUptimeStrip(days: Int) -> String {
            L10n.string("status.card.uptimeStrip", days)
        }
        /// `status.component.degraded` — Degraded
        public static var componentDegraded: String {
            L10n.string("status.component.degraded")
        }
        /// `status.component.maintenance` — Maintenance
        public static var componentMaintenance: String {
            L10n.string("status.component.maintenance")
        }
        /// `status.component.majorOutage` — Major Outage
        public static var componentMajorOutage: String {
            L10n.string("status.component.majorOutage")
        }
        /// `status.component.operational` — Operational
        public static var componentOperational: String {
            L10n.string("status.component.operational")
        }
        /// `status.component.other` — Other
        public static var componentOther: String {
            L10n.string("status.component.other")
        }
        /// `status.component.partialOutage` — Partial Outage
        public static var componentPartialOutage: String {
            L10n.string("status.component.partialOutage")
        }
        /// `status.indicator.critical` — Critical
        public static var indicatorCritical: String {
            L10n.string("status.indicator.critical")
        }
        /// `status.indicator.loading` — Loading
        public static var indicatorLoading: String {
            L10n.string("status.indicator.loading")
        }
        /// `status.indicator.maintenance` — Maintenance
        public static var indicatorMaintenance: String {
            L10n.string("status.indicator.maintenance")
        }
        /// `status.indicator.major` — Major
        public static var indicatorMajor: String {
            L10n.string("status.indicator.major")
        }
        /// `status.indicator.minor` — Minor
        public static var indicatorMinor: String {
            L10n.string("status.indicator.minor")
        }
        /// `status.overview.checking` — Checking
        public static var overviewChecking: String {
            L10n.string("status.overview.checking")
        }
        /// `status.overview.degraded` — Degraded
        public static var overviewDegraded: String {
            L10n.string("status.overview.degraded")
        }
        /// `status.overview.down` — Down
        public static var overviewDown: String {
            L10n.string("status.overview.down")
        }
        /// `status.overview.enableProvider` — Enable a core provider in Settings to show service status.
        public static var overviewEnableProvider: String {
            L10n.string("status.overview.enableProvider")
        }
        /// `status.overview.fetchFailed` — Fetch failed
        public static var overviewFetchFailed: String {
            L10n.string("status.overview.fetchFailed")
        }
        /// `status.overview.maintenance` — Maintenance
        public static var overviewMaintenance: String {
            L10n.string("status.overview.maintenance")
        }
        /// `status.overview.needsAttention` — Needs attention
        public static var overviewNeedsAttention: String {
            L10n.string("status.overview.needsAttention")
        }
        /// `status.overview.operational` — Operational
        public static var overviewOperational: String {
            L10n.string("status.overview.operational")
        }
        /// `status.overview.partialOutage` — Partial outage
        public static var overviewPartialOutage: String {
            L10n.string("status.overview.partialOutage")
        }
        /// `status.overview.refreshing` — Refreshing
        public static var overviewRefreshing: String {
            L10n.string("status.overview.refreshing")
        }
        /// `status.overview.title` — Status
        public static var overviewTitle: String {
            L10n.string("status.overview.title")
        }
    }

    public enum Usage {
        /// `usage.harnessMix.activeCount` — {count, plural, one {1 harness} other {# harnesses}} active in range
        public static func harnessMixActiveCount(count: Int) -> String {
            L10n.string("usage.harnessMix.activeCount", count)
        }
        /// `usage.harnessMix.byRealTokens` — by real tokens
        public static var harnessMixByRealTokens: String {
            L10n.string("usage.harnessMix.byRealTokens")
        }
        /// `usage.harnessMix.empty` — No harness traffic in this range
        public static var harnessMixEmpty: String {
            L10n.string("usage.harnessMix.empty")
        }
        /// `usage.harnessMix.title` — HARNESS MIX
        public static var harnessMixTitle: String {
            L10n.string("usage.harnessMix.title")
        }
        /// `usage.hero.allRequestsPriced` — all requests priced
        public static var heroAllRequestsPriced: String {
            L10n.string("usage.hero.allRequestsPriced")
        }
        /// `usage.hero.inSelectedRange` — in selected range
        public static var heroInSelectedRange: String {
            L10n.string("usage.hero.inSelectedRange")
        }
        /// `usage.hero.noPricedRequests` — no priced requests
        public static var heroNoPricedRequests: String {
            L10n.string("usage.hero.noPricedRequests")
        }
        /// `usage.hero.noTrafficInRange` — no traffic in range
        public static var heroNoTrafficInRange: String {
            L10n.string("usage.hero.noTrafficInRange")
        }
        /// `usage.hero.requests` — REQUESTS
        public static var heroRequests: String {
            L10n.string("usage.hero.requests")
        }
        /// `usage.hero.tokenComposition` — Token composition
        public static var heroTokenComposition: String {
            L10n.string("usage.hero.tokenComposition")
        }
        /// `usage.hero.totalCost` — TOTAL COST
        public static var heroTotalCost: String {
            L10n.string("usage.hero.totalCost")
        }
        /// `usage.hero.unpricedBadge` — {count} unpriced
        public static func heroUnpricedBadge(count: Int) -> String {
            L10n.string("usage.hero.unpricedBadge", count)
        }
        /// `usage.hero.unpricedHelp` — {count, plural, one {1 request} other {# requests}} had no usable price and contribute $0.
        public static func heroUnpricedHelp(count: Int) -> String {
            L10n.string("usage.hero.unpricedHelp", count)
        }
        /// `usage.ledgerUnavailable.detail` — The per-request ledger under ~/.vibebar could not be opened, so only live cost cards are available this session.
        public static var ledgerUnavailableDetail: String {
            L10n.string("usage.ledgerUnavailable.detail")
        }
        /// `usage.ledgerUnavailable.title` — Usage ledger unavailable
        public static var ledgerUnavailableTitle: String {
            L10n.string("usage.ledgerUnavailable.title")
        }
        /// `usage.noHarnessSelected.detail` — The All harnesses chip is a switch: click it again to put every harness back in the query.
        public static var noHarnessSelectedDetail: String {
            L10n.string("usage.noHarnessSelected.detail")
        }
        /// `usage.noHarnessSelected.title` — No harness selected — pick one above
        public static var noHarnessSelectedTitle: String {
            L10n.string("usage.noHarnessSelected.title")
        }
        /// `usage.requestCount` — {count} requests
        public static func requestCount(count: String) -> String {
            L10n.string("usage.requestCount", count)
        }
        /// `usage.whenYouUse.everything` — When you use everything
        public static var whenYouUseEverything: String {
            L10n.string("usage.whenYouUse.everything")
        }
        /// `usage.whenYouUse.googleAI` — When you use Google AI
        public static var whenYouUseGoogleAI: String {
            L10n.string("usage.whenYouUse.googleAI")
        }
        /// `usage.whenYouUse.spaceXAI` — When you use SpaceXAI
        public static var whenYouUseSpaceXAI: String {
            L10n.string("usage.whenYouUse.spaceXAI")
        }
    }

    public enum Workbench {
        /// `workbench.placeholder.resets` — Cycle, refill and forecast views are on their way.
        public static var placeholderResets: String {
            L10n.string("workbench.placeholder.resets")
        }
        /// `workbench.placeholder.sessionManager` — Browsing and searching local Codex and Claude Code sessions is on its way.
        public static var placeholderSessionManager: String {
            L10n.string("workbench.placeholder.sessionManager")
        }
        /// `workbench.placeholder.settings` — Configure Vibe Bar and its connected providers.
        public static var placeholderSettings: String {
            L10n.string("workbench.placeholder.settings")
        }
        /// `workbench.placeholder.skillsManager` — Reviewing and organizing installed agent skills is on its way.
        public static var placeholderSkillsManager: String {
            L10n.string("workbench.placeholder.skillsManager")
        }
        /// `workbench.placeholder.usageStats` — Full-window usage and cost analytics are on their way.
        public static var placeholderUsageStats: String {
            L10n.string("workbench.placeholder.usageStats")
        }
    }
}

extension L10n {
    /// Every key the catalog defines, for the tests that assert the
    /// shipped `.strings` resolve and that no key is unreachable.
    static let allKeys: [String] = [
        "common.date.month.1",
        "common.date.month.10",
        "common.date.month.11",
        "common.date.month.12",
        "common.date.month.2",
        "common.date.month.3",
        "common.date.month.4",
        "common.date.month.5",
        "common.date.month.6",
        "common.date.month.7",
        "common.date.month.8",
        "common.date.month.9",
        "common.date.monthDayTime",
        "common.date.monthDayYearTime",
        "common.duration.days",
        "common.duration.daysHours",
        "common.duration.hours",
        "common.duration.hoursMinutes",
        "common.duration.lessThanMinute",
        "common.duration.minutes",
        "common.duration.now",
        "common.off",
        "common.on",
        "common.openSettings",
        "common.percent",
        "common.refresh",
        "common.refreshSection",
        "common.retry",
        "common.updated.daysAgo",
        "common.updated.hoursAgo",
        "common.updated.justNow",
        "common.updated.minutesAgo",
        "common.updated.never",
        "common.updated.secondsAgo",
        "cost.allProviders",
        "cost.empty.antigravity",
        "cost.empty.claude",
        "cost.empty.codex",
        "cost.empty.gemini",
        "cost.empty.genericCLI",
        "cost.empty.grok",
        "cost.fullCharts",
        "cost.gemini.emptyDetail",
        "cost.gemini.emptyTitle",
        "cost.googleAI.empty",
        "cost.googleAI.title",
        "cost.history.allProviders",
        "cost.metric.peakDay",
        "cost.metric.peakTokenDay",
        "cost.metric.sevenDay",
        "cost.metric.sevenDayTokens",
        "cost.metric.thirtyDay",
        "cost.metric.thirtyDayTokens",
        "cost.metric.today",
        "cost.metric.todayTokens",
        "cost.metric.totalCost",
        "cost.metric.totalTokens",
        "cost.metric.yesterday",
        "cost.metric.yesterdayTokens",
        "cost.modelRanking.allProvidersAllTime",
        "cost.modelRanking.allTime",
        "cost.modelRanking.rank",
        "cost.modelRanking.title",
        "cost.noUsageYet",
        "cost.notTracked",
        "cost.openFullCharts",
        "cost.provider.title",
        "cost.refreshData",
        "cost.refreshProvider",
        "cost.spaceXAI.empty",
        "cost.spaceXAI.title",
        "cost.timeframe.all",
        "cost.timeframe.month",
        "cost.timeframe.monthShort",
        "cost.timeframe.today",
        "cost.timeframe.week",
        "cost.timeframe.weekShort",
        "cost.timeframe.yesterday",
        "cost.title",
        "cost.topModel.share",
        "cost.topModel.title",
        "cost.topModel.window",
        "error.credentialRejected",
        "error.needsLogin",
        "error.network",
        "error.networkDetail",
        "error.noCredential",
        "error.notImplemented",
        "error.parseFailure",
        "error.rateLimited",
        "error.unknown",
        "error.unknownDetail",
        "onboarding.apiKeys.intro",
        "onboarding.apiKeys.showOnMiscPage",
        "onboarding.back",
        "onboarding.continue",
        "onboarding.cookies.batchScope",
        "onboarding.cookies.importFromBrowser",
        "onboarding.cookies.importGemini",
        "onboarding.cookies.importGrok",
        "onboarding.cookies.importing",
        "onboarding.cookies.intro",
        "onboarding.cookies.notImported",
        "onboarding.cookies.openWebViewLogin",
        "onboarding.cookies.saved",
        "onboarding.cookies.signInFirst",
        "onboarding.done.apiKeyProviders",
        "onboarding.done.browserCookies",
        "onboarding.done.cookieCount",
        "onboarding.done.footer",
        "onboarding.done.intro",
        "onboarding.done.launchAtLogin",
        "onboarding.done.miscCount",
        "onboarding.done.modelPricing",
        "onboarding.done.noneShown",
        "onboarding.done.pricingBundled",
        "onboarding.done.pricingMerged",
        "onboarding.done.subscriptions",
        "onboarding.finish",
        "onboarding.pricing.fetchNow",
        "onboarding.pricing.fetching",
        "onboarding.pricing.footer",
        "onboarding.pricing.interval.hour",
        "onboarding.pricing.interval.hours",
        "onboarding.pricing.intro",
        "onboarding.pricing.merged",
        "onboarding.pricing.notFetched",
        "onboarding.pricing.source.failed",
        "onboarding.pricing.source.models",
        "onboarding.pricing.source.notRefreshed",
        "onboarding.pricing.source.unchanged",
        "onboarding.skip",
        "onboarding.step.apiKeyProviders.subtitle",
        "onboarding.step.apiKeyProviders.title",
        "onboarding.step.browserCookies.subtitle",
        "onboarding.step.browserCookies.title",
        "onboarding.step.done.subtitle",
        "onboarding.step.done.title",
        "onboarding.step.pricing.subtitle",
        "onboarding.step.pricing.title",
        "onboarding.step.subscriptions.subtitle",
        "onboarding.step.subscriptions.title",
        "onboarding.step.welcome.subtitle",
        "onboarding.step.welcome.title",
        "onboarding.subscriptions.claude.detected",
        "onboarding.subscriptions.claude.missing",
        "onboarding.subscriptions.claude.web",
        "onboarding.subscriptions.codex.detected",
        "onboarding.subscriptions.codex.missing",
        "onboarding.subscriptions.codex.web",
        "onboarding.subscriptions.gemini.hint",
        "onboarding.subscriptions.grok.detected",
        "onboarding.subscriptions.grok.missing",
        "onboarding.subscriptions.intro",
        "onboarding.subscriptions.productLine.claude",
        "onboarding.subscriptions.productLine.codex",
        "onboarding.subscriptions.productLine.gemini",
        "onboarding.subscriptions.productLine.grok",
        "onboarding.subscriptions.showInOverview",
        "onboarding.title",
        "onboarding.welcome.cost.detail",
        "onboarding.welcome.cost.title",
        "onboarding.welcome.footer",
        "onboarding.welcome.intro",
        "onboarding.welcome.mcp.detail",
        "onboarding.welcome.mcp.title",
        "onboarding.welcome.quotas.detail",
        "onboarding.welcome.quotas.title",
        "onboarding.welcome.sessions.detail",
        "onboarding.welcome.sessions.title",
        "platform.macos.launchAtLogin.detail",
        "platform.macos.launchAtLogin.enabled",
        "platform.macos.launchAtLogin.off",
        "platform.macos.launchAtLogin.subtitle",
        "platform.macos.launchAtLogin.title",
        "platform.macos.launchAtLogin.toggle",
        "popover.header.machinesSubtitle",
        "popover.header.miscSubtitle",
        "popover.header.overviewSubtitle",
        "popover.refreshGoogleAI",
        "popover.refreshSpaceXAI",
        "popover.showPage",
        "popover.tab.machines",
        "popover.tab.misc",
        "popover.tab.miscShort",
        "popover.tab.overview",
        "quota.bucket.noResetInfo",
        "quota.bucket.resetsIn",
        "quota.empty.needsLogin.detail",
        "quota.empty.needsLogin.headline",
        "quota.empty.network.detail",
        "quota.empty.network.headline",
        "quota.empty.noAccount.detail",
        "quota.empty.noAccount.headline",
        "quota.empty.parseChanged.detail",
        "quota.empty.parseChanged.headline",
        "quota.empty.rateLimited.detail",
        "quota.empty.rateLimited.headline",
        "quota.forecast.confidence.high",
        "quota.forecast.confidence.learning",
        "quota.forecast.confidence.medium",
        "quota.forecast.guidance.atRisk",
        "quota.forecast.guidance.available",
        "quota.forecast.guidance.surplus",
        "quota.forecast.guidance.usedAvailable",
        "quota.forecast.guidance.usedSurplus",
        "quota.forecast.guidance.usedWithinTarget",
        "quota.forecast.guidance.watch",
        "quota.forecast.guidance.withinTarget",
        "quota.forecast.reset.atRisk",
        "quota.forecast.reset.enough",
        "quota.forecast.reset.learning",
        "quota.forecast.reset.surplus",
        "quota.forecast.reset.watch",
        "quota.forecast.status.atRisk",
        "quota.forecast.status.enough",
        "quota.forecast.status.learning",
        "quota.forecast.status.surplus",
        "quota.forecast.status.watch",
        "quota.forecast.useUp.beforeReset",
        "quota.forecast.useUp.couldRunOut",
        "quota.forecast.useUp.estimated",
        "quota.forecast.useUp.lastsUntilReset",
        "quota.forecast.useUp.uncertain",
        "quota.forecast.value.left",
        "quota.forecast.value.used",
        "quota.forecast.verdict.atRisk",
        "quota.forecast.verdict.enough",
        "quota.forecast.verdict.learning",
        "quota.forecast.verdict.surplus",
        "quota.forecast.verdict.watch",
        "quota.freshness.age.days",
        "quota.freshness.age.hours",
        "quota.freshness.age.minutes",
        "quota.freshness.age.seconds",
        "quota.freshness.dataAge",
        "quota.freshness.defaultHelp",
        "quota.freshness.line",
        "quota.freshness.noCachedData",
        "quota.freshness.refreshFailed",
        "quota.freshness.refreshFailedAgo",
        "quota.freshness.staleNeverUpdated",
        "quota.freshness.staleUpdatedAgo",
        "quota.group.allModels",
        "quota.group.daily",
        "quota.group.fiveHours",
        "quota.group.monthly",
        "quota.group.noUtilization",
        "quota.group.other",
        "quota.group.otherModels",
        "quota.group.weekly",
        "quota.group.weeklyCredits",
        "quota.login.claude",
        "quota.login.codex",
        "quota.login.cursor",
        "quota.login.grok",
        "quota.login.misc",
        "quota.mode.remaining",
        "quota.mode.used",
        "quota.pace.lastsUntilReset",
        "quota.pace.runsOutIn",
        "quota.perModelLimits",
        "quota.reset.in",
        "quota.reset.passed",
        "quota.reset.passedAt",
        "quota.resetCredits.available",
        "quota.resetCredits.availableWithExpiry",
        "quota.resetCredits.count",
        "quota.resetCredits.title",
        "quota.resetHistory.a11y.empty",
        "quota.resetHistory.a11y.more",
        "quota.resetHistory.a11y.summary",
        "quota.resetHistory.a11y.truncation",
        "quota.resetHistory.axis.cycle",
        "quota.resetHistory.axis.cycleHelp",
        "quota.resetHistory.axis.time",
        "quota.resetHistory.axis.timeHelp",
        "quota.resetHistory.axisCyclesBack",
        "quota.resetHistory.axisNow",
        "quota.resetHistory.lane.emptyState",
        "quota.resetHistory.lane.noCycles",
        "quota.resetHistory.lane.spokenNoCycles",
        "quota.resetHistory.lane.spokenWaste",
        "quota.resetHistory.lane.wasteSummary",
        "quota.resetHistory.reset.earlyClockRestarted",
        "quota.resetHistory.reset.earlyClockUnchanged",
        "quota.resetHistory.reset.earlyUnclear",
        "quota.resetHistory.spoken.allCycles",
        "quota.resetHistory.spoken.allTime",
        "quota.resetHistory.spoken.eightCycles",
        "quota.resetHistory.spoken.eightWeeks",
        "quota.resetHistory.spoken.fourCycles",
        "quota.resetHistory.spoken.fourWeeks",
        "quota.resetHistory.spoken.twelveCycles",
        "quota.resetHistory.spoken.twelveWeeks",
        "quota.resetHistory.title",
        "quota.resetHistory.totals.headline",
        "quota.resetHistory.totals.none",
        "quota.resetHistory.truncation",
        "quota.resetHistory.verdict.clean",
        "quota.resetHistory.verdict.leaky",
        "quota.resetHistory.verdict.noCycles",
        "quota.resetHistory.verdict.noQuota",
        "quota.resetHistory.verdict.wasteful",
        "quota.resetHistory.window.all",
        "quota.resetHistory.window.eightWeeks",
        "quota.resetHistory.window.fourWeeks",
        "quota.resetHistory.window.twelveWeeks",
        "quota.upcoming.axisDays",
        "quota.upcoming.axisHours",
        "quota.upcoming.empty",
        "quota.upcoming.forecastAtReset",
        "quota.upcoming.gain",
        "quota.upcoming.horizon",
        "quota.upcoming.leftAndGain",
        "quota.upcoming.markerHelp",
        "quota.upcoming.resetsAt",
        "quota.upcoming.title",
        "quota.update.failed",
        "settings.language.caption",
        "settings.language.system",
        "settings.language.title",
        "status.card.componentCount",
        "status.card.components",
        "status.card.noIncidents",
        "status.card.openIncident",
        "status.card.openStatusPage",
        "status.card.refresh",
        "status.card.statusPageFallback",
        "status.card.title",
        "status.card.updatedHoursAgo",
        "status.card.updatedJustNow",
        "status.card.updatedMinutesAgo",
        "status.card.uptime",
        "status.card.uptimeStrip",
        "status.component.degraded",
        "status.component.maintenance",
        "status.component.majorOutage",
        "status.component.operational",
        "status.component.other",
        "status.component.partialOutage",
        "status.indicator.critical",
        "status.indicator.loading",
        "status.indicator.maintenance",
        "status.indicator.major",
        "status.indicator.minor",
        "status.overview.checking",
        "status.overview.degraded",
        "status.overview.down",
        "status.overview.enableProvider",
        "status.overview.fetchFailed",
        "status.overview.maintenance",
        "status.overview.needsAttention",
        "status.overview.operational",
        "status.overview.partialOutage",
        "status.overview.refreshing",
        "status.overview.title",
        "usage.harnessMix.activeCount",
        "usage.harnessMix.byRealTokens",
        "usage.harnessMix.empty",
        "usage.harnessMix.title",
        "usage.hero.allRequestsPriced",
        "usage.hero.inSelectedRange",
        "usage.hero.noPricedRequests",
        "usage.hero.noTrafficInRange",
        "usage.hero.requests",
        "usage.hero.tokenComposition",
        "usage.hero.totalCost",
        "usage.hero.unpricedBadge",
        "usage.hero.unpricedHelp",
        "usage.ledgerUnavailable.detail",
        "usage.ledgerUnavailable.title",
        "usage.noHarnessSelected.detail",
        "usage.noHarnessSelected.title",
        "usage.requestCount",
        "usage.whenYouUse.everything",
        "usage.whenYouUse.googleAI",
        "usage.whenYouUse.spaceXAI",
        "workbench.placeholder.resets",
        "workbench.placeholder.sessionManager",
        "workbench.placeholder.settings",
        "workbench.placeholder.skillsManager",
        "workbench.placeholder.usageStats",
    ]

    /// Keys whose value is a plural and therefore lives in the
    /// `.stringsdict` rather than the `.strings` file.
    static let pluralKeys: [String] = [
        "common.updated.daysAgo",
        "common.updated.hoursAgo",
        "common.updated.minutesAgo",
        "quota.perModelLimits",
        "quota.resetCredits.available",
        "quota.resetHistory.lane.wasteSummary",
        "quota.resetHistory.totals.headline",
        "quota.resetHistory.verdict.leaky",
        "quota.resetHistory.verdict.wasteful",
        "status.card.componentCount",
        "usage.harnessMix.activeCount",
        "usage.hero.unpricedHelp",
    ]
}
